## new 회원을 위한 추천 분류모델링

### 분류모델링

#### 군집별 데이터(중복제거) 확인

In [105]:
import pandas as pd


wine_df = pd.read_csv('wine_df_final_clustering.csv', index_col = 0)
wine_df.head()

,와인이름,영어이름,와인타입,"나라, 와이너리",포도종,도수,당도,산도,바디,탄닌,...,도수_cate2,당도_cate2,산도_cate2,바디_cate2,타입_cate2,대표 중분류 아로마1,대표 중분류 아로마2,추천솔루션 군집화,상황별추천 군집화,상황별추천 군집화_n
0,이기갈 꼬뜨 뒤 론 레드,E.Guigal Cotes du Rhone Rouge,레드 와인,프랑스 > 론 / 이 기갈,"시라 49%, 그르나쉬 48%, 무르베드르 3%",13.0,1,2,4,1.0,...,적당함,달지 않음,적당함,끈적임,레드,빨간 과일,허베이셔스,대중적인 레드러버,가족과 함께,0
1,이기갈 꼬뜨 뒤 론 화이트,E.Guigal Cotes du Rhone Blanc,화이트 와인,프랑스 > 론 / 이 기갈,"비오니에 70%, 루산느 10%, 마르산느 9%, 끌레레뜨 8%, 부르불랑 3%",13.0,1,3,3,NaN,...,적당함,달지 않음,신맛,적당함,화이트,꽃,핵과,대중적인 화이트 러버,가족과 함께,0
2,이기갈 꼬뜨 로띠 ‘브륀 & 블롱드’,E.Guigal Cot-Rotie ‘Brune & Blonde de Guigal’,레드 와인,프랑스 > 론 / 이 기갈,"시라 96%, 비오니에 4%",13.0,1,3,5,1.0,...,적당함,달지 않음,신맛,끈적임,레드,자연(Earthy),오크(Oak),대중적인 레드러버,가족과 함께,0
3,이기갈 꼬뜨 로띠 ‘샤또 당퓌’,E.Guigal Cote-Rotie ‘Chateau d’Ampuis’,레드 와인,프랑스 > 론 / 이 기갈,"시라 93%, 비오니에 7%",13.0,1,3,5,1.0,...,적당함,달지 않음,신맛,끈적임,레드,오크(Oak),녹색 과일,대중적인 레드러버,가족과 함께,0
4,이기갈 꽁드리유,E.Guigal Condrieu,화이트 와인,프랑스 > 론 / 이 기갈,비오니에 100%,13.0,1,3,4,NaN,...,적당함,달지 않음,신맛,끈적임,화이트,핵과,NaN,대중적인 화이트 러버,가족과 함께,0

In [106]:
wine_df.columns

Index(['와인이름', '영어이름', '와인타입', '나라, 와이너리', '포도종', '도수', '당도', '산도', '바디', '탄닌',
       '와이너리이름', '와이너리설명', '와이너리특징', '아로마 딕셔너리', '곁들일 음식', '음식', '아로마 중분류',
       '아로마 소분류', '대표 중분류 아로마', '도수_cate', '당도_cate', '산도_cate', '바디_cate',
       '타입_cate', '도수_cate2', '당도_cate2', '산도_cate2', '바디_cate2', '타입_cate2',
       '대표 중분류 아로마1', '대표 중분류 아로마2', '추천솔루션 군집화', '상황별추천 군집화', '상황별추천 군집화_n'],
      dtype='object')

In [107]:
import numpy as np
wine_df['추천솔루션 군집화_n'] = np.nan

for i, clu in enumerate(wine_df['추천솔루션 군집화'].unique()):
    wine_df.loc[wine_df['추천솔루션 군집화'] == clu, '추천솔루션 군집화_n'] = i
    
wine_df['추천솔루션 군집화_n'] = wine_df['추천솔루션 군집화_n'].astype(int)
wine_df

,와인이름,영어이름,와인타입,"나라, 와이너리",포도종,도수,당도,산도,바디,탄닌,...,당도_cate2,산도_cate2,바디_cate2,타입_cate2,대표 중분류 아로마1,대표 중분류 아로마2,추천솔루션 군집화,상황별추천 군집화,상황별추천 군집화_n,추천솔루션 군집화_n
0,이기갈 꼬뜨 뒤 론 레드,E.Guigal Cotes du Rhone Rouge,레드 와인,프랑스 > 론 / 이 기갈,"시라 49%, 그르나쉬 48%, 무르베드르 3%",13.0,1,2,4,1.0,...,달지 않음,적당함,끈적임,레드,빨간 과일,허베이셔스,대중적인 레드러버,가족과 함께,0,0
1,이기갈 꼬뜨 뒤 론 화이트,E.Guigal Cotes du Rhone Blanc,화이트 와인,프랑스 > 론 / 이 기갈,"비오니에 70%, 루산느 10%, 마르산느 9%, 끌레레뜨 8%, 부르불랑 3%",13.0,1,3,3,NaN,...,달지 않음,신맛,적당함,화이트,꽃,핵과,대중적인 화이트 러버,가족과 함께,0,1
2,이기갈 꼬뜨 로띠 ‘브륀 & 블롱드’,E.Guigal Cot-Rotie ‘Brune & Blonde de Guigal’,레드 와인,프랑스 > 론 / 이 기갈,"시라 96%, 비오니에 4%",13.0,1,3,5,1.0,...,달지 않음,신맛,끈적임,레드,자연(Earthy),오크(Oak),대중적인 레드러버,가족과 함께,0,0
3,이기갈 꼬뜨 로띠 ‘샤또 당퓌’,E.Guigal Cote-Rotie ‘Chateau d’Ampuis’,레드 와인,프랑스 > 론 / 이 기갈,"시라 93%, 비오니에 7%",13.0,1,3,5,1.0,...,달지 않음,신맛,끈적임,레드,오크(Oak),녹색 과일,대중적인 레드러버,가족과 함께,0,0
4,이기갈 꽁드리유,E.Guigal Condrieu,화이트 와인,프랑스 > 론 / 이 기갈,비오니에 100%,13.0,1,3,4,NaN,...,달지 않음,신맛,끈적임,화이트,핵과,NaN,대중적인 화이트 러버,가족과 함께,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
320,까테나 자파타 까테나 말벡,Catena Zapata Catena Malbec,레드 와인,아르헨티나 > 멘도자 / 까테나 자파타,말백 100%,14.0,1,3,3,1.0,...,달지 않음,신맛,적당함,레드,자연(Earthy),오크(Oak),대중적인 레드러버,술른이 연인과함께,3,0
321,까테나 자파타 까테나 알타 샤르도네,Catena Zapata Catena Alta Chardonnay,화이트 와인,아르헨티나 > 멘도자 / 까테나 자파타,샤르도네 100%,13.0,2,3,4,NaN,...,달지 않음,신맛,끈적임,화이트,자연(Earthy),녹색 과일,대중적인 화이트 러버,가족과 함께,0,1
322,까테나 자파타 까테나 알타 말벡,Catena Zapata Catena Alta Malbec,레드 와인,아르헨티나 > 멘도자 / 까테나 자파타,말백 100%,14.0,1,3,4,1.0,...,달지 않음,신맛,끈적임,레드,오크(Oak),빨간 과일,대중적인 레드러버,술른이 연인과함께,3,0
323,까테나 자파타 니카시아 말벡,Catena Zapata Nicasia Malbec,레드 와인,아르헨티나 > 멘도자 / 까테나 자파타,말벡 100%,14.0,1,3,5,1.0,...,달지 않음,신맛,끈적임,레드,오크(Oak),꽃,대중적인 레드러버,술른이 연인과함께,3,0
324,까테나 자파타 아르헨티노 말벡,Catena Zapata Argentino Malbec,레드 와인,아르헨티나 > 멘도자 / 까테나 자파타,말벡 100%,14.0,1,4,5,1.0,...,달지 않음,신맛,끈적임,레드,녹색 과일,빨간 과일,대중적인 레드러버,술른이 연인과함께,3,0

In [108]:
wine_df[['추천솔루션 군집화','추천솔루션 군집화_n']].value_counts()

추천솔루션 군집화           추천솔루션 군집화_n
대중적인 레드러버           0              168
대중적인 화이트 러버         1               92
당뇨병 화이트 술청년         3               25
숨은 고수인 척하는 당뇨병 술청년  2               19
대중없는 당뇨병 술청년        5                9
숨은 고수 술린이           4                9
올~ 쎈데! 술부심 쌉가능 술른이  6                3
dtype: int64

In [109]:
wine_df_model = wine_df[['와인이름','도수', '당도', '산도', '바디','타입_cate','추천솔루션 군집화', '추천솔루션 군집화_n']]
wine_df_model

                     와인이름    도수  당도  산도  바디  타입_cate    추천솔루션 군집화  추천솔루션 군집화_n
0           이기갈 꼬뜨 뒤 론 레드  13.0   1   2   4        1    대중적인 레드러버            0
1          이기갈 꼬뜨 뒤 론 화이트  13.0   1   3   3        2  대중적인 화이트 러버            1
2    이기갈 꼬뜨 로띠 ‘브륀 & 블롱드’  13.0   1   3   5        1    대중적인 레드러버            0
3       이기갈 꼬뜨 로띠 ‘샤또 당퓌’  13.0   1   3   5        1    대중적인 레드러버            0
4                이기갈 꽁드리유  13.0   1   3   4        2  대중적인 화이트 러버            1
..                    ...   ...  ..  ..  ..      ...          ...          ...
320        까테나 자파타 까테나 말벡  14.0   1   3   3        1    대중적인 레드러버            0
321   까테나 자파타 까테나 알타 샤르도네  13.0   2   3   4        2  대중적인 화이트 러버            1
322     까테나 자파타 까테나 알타 말벡  14.0   1   3   4        1    대중적인 레드러버            0
323       까테나 자파타 니카시아 말벡  14.0   1   3   5        1    대중적인 레드러버            0
324      까테나 자파타 아르헨티노 말벡  14.0   1   4   5        1    대중적인 레드러버            0

[325 rows x 8 columns]

In [110]:
wine_df_model_test = wine_df_model.drop(columns = ['와인이름'])
for i in range(7):
    df = wine_df_model_test[wine_df_model_test['추천솔루션 군집화_n'] == i].drop_duplicates()
    df = df.sort_values(['도수','타입_cate','당도','산도','바디'])
    display(df)

       도수  당도  산도  바디  타입_cate  추천솔루션 군집화  추천솔루션 군집화_n
9    12.0   1   3   4        1  대중적인 레드러버            0
6    12.0   1   3   5        1  대중적인 레드러버            0
290  13.0   1   2   3        1  대중적인 레드러버            0
0    13.0   1   2   4        1  대중적인 레드러버            0
312  13.0   1   3   3        1  대중적인 레드러버            0
5    13.0   1   3   4        1  대중적인 레드러버            0
2    13.0   1   3   5        1  대중적인 레드러버            0
64   13.0   2   3   4        1  대중적인 레드러버            0
254  14.0   1   1   4        1  대중적인 레드러버            0
295  14.0   1   2   4        1  대중적인 레드러버            0
318  14.0   1   3   3        1  대중적인 레드러버            0
18   14.0   1   3   4        1  대중적인 레드러버            0
10   14.0   1   3   5        1  대중적인 레드러버            0
324  14.0   1   4   5        1  대중적인 레드러버            0
303  14.0   2   2   4        1  대중적인 레드러버            0
301  14.0   2   3   4        1  대중적인 레드러버            0
292  15.0   1   2   4        1  대중적인 레드러버            0
69   15.0   1   3   4        1  대중적인 레드러버            0
107  15.0   1   3   5        1  대중적인 레드러버            0

       도수  당도  산도  바디  타입_cate    추천솔루션 군집화  추천솔루션 군집화_n
66    9.0   2   3   4        3  대중적인 화이트 러버            1
277  10.0   1   4   3        2  대중적인 화이트 러버            1
76   10.0   2   3   3        2  대중적인 화이트 러버            1
52   10.0   1   3   3        3  대중적인 화이트 러버            1
111  10.0   2   3   3        3  대중적인 화이트 러버            1
26   11.0   1   3   4        2  대중적인 화이트 러버            1
238  11.0   2   3   4        2  대중적인 화이트 러버            1
92   11.0   2   3   3        3  대중적인 화이트 러버            1
135  12.0   1   3   3        2  대중적인 화이트 러버            1
24   12.0   1   3   4        2  대중적인 화이트 러버            1
307  12.0   1   4   2        2  대중적인 화이트 러버            1
284  12.0   2   3   2        2  대중적인 화이트 러버            1
67   12.0   2   3   3        2  대중적인 화이트 러버            1
198  12.0   1   3   3        3  대중적인 화이트 러버            1
56   12.0   1   3   4        3  대중적인 화이트 러버            1
313  12.0   1   4   2        3  대중적인 화이트 러버            1
315  12.0   1   4   3        3  대중적인 화이트 러버            1
298  13.0   1   3   2        2  대중적인 화이트 러버            1
1    13.0   1   3   3        2  대중적인 화이트 러버            1
4    13.0   1   3   4        2  대중적인 화이트 러버            1
258  13.0   1   3   5        2  대중적인 화이트 러버            1
276  13.0   1   4   2        2  대중적인 화이트 러버            1
291  13.0   1   4   3        2  대중적인 화이트 러버            1
282  13.0   2   3   2        2  대중적인 화이트 러버            1
321  13.0   2   3   4        2  대중적인 화이트 러버            1
53   13.0   1   3   3        3  대중적인 화이트 러버            1
294  14.0   1   3   2        2  대중적인 화이트 러버            1
19   14.0   1   3   3        2  대중적인 화이트 러버            1
51   14.0   1   3   4        2  대중적인 화이트 러버            1
274  14.0   2   4   3        2  대중적인 화이트 러버            1
256  15.0   1   3   4        2  대중적인 화이트 러버            1

       도수  당도  산도  바디  타입_cate           추천솔루션 군집화  추천솔루션 군집화_n
96    1.0   1   3   4        1  숨은 고수인 척하는 당뇨병 술청년            2
14    6.0   4   3   3        1  숨은 고수인 척하는 당뇨병 술청년            2
16    6.0   5   3   3        1  숨은 고수인 척하는 당뇨병 술청년            2
89    7.0   1   3   4        1  숨은 고수인 척하는 당뇨병 술청년            2
87    7.0   1   3   5        1  숨은 고수인 척하는 당뇨병 술청년            2
81   12.0   3   2   3        1  숨은 고수인 척하는 당뇨병 술청년            2
85   14.0   3   3   4        1  숨은 고수인 척하는 당뇨병 술청년            2
83   14.0   3   3   5        1  숨은 고수인 척하는 당뇨병 술청년            2
205  15.0   5   3   5        1  숨은 고수인 척하는 당뇨병 술청년            2

       도수  당도  산도  바디  타입_cate    추천솔루션 군집화  추천솔루션 군집화_n
278   8.0   4   4   3        2  당뇨병 화이트 술청년            3
80    8.0   5   2   5        2  당뇨병 화이트 술청년            3
75    8.0   5   3   3        2  당뇨병 화이트 술청년            3
77    8.0   5   3   4        2  당뇨병 화이트 술청년            3
68    9.0   4   3   3        2  당뇨병 화이트 술청년            3
155   9.0   5   3   2        2  당뇨병 화이트 술청년            3
78   10.0   4   3   4        2  당뇨병 화이트 술청년            3
79   10.0   5   2   4        2  당뇨병 화이트 술청년            3
287  10.0   5   3   4        2  당뇨병 화이트 술청년            3
122  11.0   5   3   4        2  당뇨병 화이트 술청년            3
121  12.0   4   3   2        2  당뇨병 화이트 술청년            3
119  12.0   4   3   3        2  당뇨병 화이트 술청년            3
124  12.0   5   3   4        2  당뇨병 화이트 술청년            3
279  12.0   5   4   4        2  당뇨병 화이트 술청년            3
283  13.0   3   3   2        2  당뇨병 화이트 술청년            3
120  13.0   3   3   3        2  당뇨병 화이트 술청년            3
15   13.0   5   3   2        2  당뇨병 화이트 술청년            3
202  13.0   5   3   4        2  당뇨병 화이트 술청년            3

      도수  당도  산도  바디  타입_cate  추천솔루션 군집화  추천솔루션 군집화_n
163  1.0   1   3   3        2  숨은 고수 술린이            4
32   1.0   1   3   4        2  숨은 고수 술린이            4
86   7.0   3   3   5        1  숨은 고수 술린이            4
88   7.0   1   3   3        2  숨은 고수 술린이            4

      도수  당도  산도  바디  타입_cate     추천솔루션 군집화  추천솔루션 군집화_n
154  5.0   5   3   2        2  대중없는 당뇨병 술청년            5
197  5.0   4   3   3        3  대중없는 당뇨병 술청년            5
172  5.0   5   3   4        3  대중없는 당뇨병 술청년            5
128  7.0   4   3   3        3  대중없는 당뇨병 술청년            5
137  7.0   5   3   4        3  대중없는 당뇨병 술청년            5
306  7.0   5   3   5        3  대중없는 당뇨병 술청년            5
173  9.0   5   3   4        3  대중없는 당뇨병 술청년            5

       도수  당도  산도  바디  타입_cate           추천솔루션 군집화  추천솔루션 군집화_n
236  16.0   1   3   5        1  올~ 쎈데! 술부심 쌉가능 술른이            6
304  17.0   2   2   4        1  올~ 쎈데! 술부심 쌉가능 술른이            6

#### 데이터 군집화 수정

도수	당도	산도	바디	타입_cate	
1.0	1	3	4	1	숨은 고수인 척하는 당뇨병 술청년	2  -> 숨은 고수 술린이, 4<br>
7.0	1	3	4	1	숨은 고수인 척하는 당뇨병 술청년	2  -> 숨은 고수 술린이, 4<br>
7.0	1	3	5	1	숨은 고수인 척하는 당뇨병 술청년	2  -> 숨은 고수 술린이, 4<br>


7.0	3	3	5	1	숨은 고수 술린이	4 -> 숨은 고수인 척하는 당뇨병 술청년, 2

In [111]:
# 해당 내용 수정

li = [[1.0,1,3,4,1],[7.0,1,3,4,1],[7.0,1,3,5,1]]
for al, sw, ac, bo, ty in li: 
    wine_df.loc[(wine_df['도수'] == al) & (wine_df['당도'] == sw) & (wine_df['산도'] == ac) & \
                (wine_df['바디'] == bo) &  (wine_df['타입_cate'] == ty), '추천솔루션 군집화' ] = '숨은 고수 술린이'
    wine_df.loc[(wine_df['도수'] == al) & (wine_df['당도'] == sw) & (wine_df['산도'] == ac) & \
                (wine_df['바디'] == bo) &  (wine_df['타입_cate'] == ty), '추천솔루션 군집화_n' ] = 4

wine_df.loc[(wine_df['도수'] == 7.0) & (wine_df['당도'] == 3) & (wine_df['산도'] == 3) & \
            (wine_df['바디'] == 5) &  (wine_df['타입_cate'] == 1), '추천솔루션 군집화' ] = '숨은 고수인 척하는 당뇨병 술청년'

wine_df.loc[(wine_df['도수'] == 7.0) & (wine_df['당도'] == 3) & (wine_df['산도'] == 3) & \
            (wine_df['바디'] == 5) &  (wine_df['타입_cate'] == 1), '추천솔루션 군집화_n' ] = 2

In [112]:
df.reset_index().loc[idx]

index                         304
도수                           17.0
당도                              2
산도                              2
바디                              4
타입_cate                         1
추천솔루션 군집화      올~ 쎈데! 술부심 쌉가능 술른이
추천솔루션 군집화_n                     6
Name: 1, dtype: object

In [113]:
# 확인

wine_df_model = wine_df[['와인이름','도수', '당도', '산도', '바디','타입_cate','추천솔루션 군집화', '추천솔루션 군집화_n']]
wine_df_model_test = wine_df_model.drop(columns = ['와인이름'])
for i in range(7):
    df = wine_df_model_test[wine_df_model_test['추천솔루션 군집화_n'] == i].drop_duplicates()
    df = df.sort_values(['도수','타입_cate','당도','산도','바디'])
    display(df)
    for idx in range(len(df)):
        i, al, sw, ac, bo, ty, x, xn = df.reset_index().loc[idx]
        leng = len(wine_df[(wine_df['도수']== al)&
                          (wine_df['당도']== sw)&
                          (wine_df['산도']== ac)&
                          (wine_df['바디']== bo)&
                          (wine_df['타입_cate']== ty)])
        print(f'{al, sw, ac, bo, ty, x, xn}: {leng}개')

       도수  당도  산도  바디  타입_cate  추천솔루션 군집화  추천솔루션 군집화_n
9    12.0   1   3   4        1  대중적인 레드러버            0
6    12.0   1   3   5        1  대중적인 레드러버            0
290  13.0   1   2   3        1  대중적인 레드러버            0
0    13.0   1   2   4        1  대중적인 레드러버            0
312  13.0   1   3   3        1  대중적인 레드러버            0
5    13.0   1   3   4        1  대중적인 레드러버            0
2    13.0   1   3   5        1  대중적인 레드러버            0
64   13.0   2   3   4        1  대중적인 레드러버            0
254  14.0   1   1   4        1  대중적인 레드러버            0
295  14.0   1   2   4        1  대중적인 레드러버            0
318  14.0   1   3   3        1  대중적인 레드러버            0
18   14.0   1   3   4        1  대중적인 레드러버            0
10   14.0   1   3   5        1  대중적인 레드러버            0
324  14.0   1   4   5        1  대중적인 레드러버            0
303  14.0   2   2   4        1  대중적인 레드러버            0
301  14.0   2   3   4        1  대중적인 레드러버            0
292  15.0   1   2   4        1  대중적인 레드러버            0
69   15.0   1   3   4        1  대중적인 레드러버            0
107  15.0   1   3   5        1  대중적인 레드러버            0

(12.0, 1, 3, 4, 1, '대중적인 레드러버', 0): 5개
(12.0, 1, 3, 5, 1, '대중적인 레드러버', 0): 2개
(13.0, 1, 2, 3, 1, '대중적인 레드러버', 0): 1개
(13.0, 1, 2, 4, 1, '대중적인 레드러버', 0): 4개
(13.0, 1, 3, 3, 1, '대중적인 레드러버', 0): 1개
(13.0, 1, 3, 4, 1, '대중적인 레드러버', 0): 53개
(13.0, 1, 3, 5, 1, '대중적인 레드러버', 0): 21개
(13.0, 2, 3, 4, 1, '대중적인 레드러버', 0): 2개
(14.0, 1, 1, 4, 1, '대중적인 레드러버', 0): 1개
(14.0, 1, 2, 4, 1, '대중적인 레드러버', 0): 2개
(14.0, 1, 3, 3, 1, '대중적인 레드러버', 0): 2개
(14.0, 1, 3, 4, 1, '대중적인 레드러버', 0): 10개
(14.0, 1, 3, 5, 1, '대중적인 레드러버', 0): 51개
(14.0, 1, 4, 5, 1, '대중적인 레드러버', 0): 1개
(14.0, 2, 2, 4, 1, '대중적인 레드러버', 0): 1개
(14.0, 2, 3, 4, 1, '대중적인 레드러버', 0): 1개
(15.0, 1, 2, 4, 1, '대중적인 레드러버', 0): 2개
(15.0, 1, 3, 4, 1, '대중적인 레드러버', 0): 1개
(15.0, 1, 3, 5, 1, '대중적인 레드러버', 0): 7개

       도수  당도  산도  바디  타입_cate    추천솔루션 군집화  추천솔루션 군집화_n
66    9.0   2   3   4        3  대중적인 화이트 러버            1
277  10.0   1   4   3        2  대중적인 화이트 러버            1
76   10.0   2   3   3        2  대중적인 화이트 러버            1
52   10.0   1   3   3        3  대중적인 화이트 러버            1
111  10.0   2   3   3        3  대중적인 화이트 러버            1
26   11.0   1   3   4        2  대중적인 화이트 러버            1
238  11.0   2   3   4        2  대중적인 화이트 러버            1
92   11.0   2   3   3        3  대중적인 화이트 러버            1
135  12.0   1   3   3        2  대중적인 화이트 러버            1
24   12.0   1   3   4        2  대중적인 화이트 러버            1
307  12.0   1   4   2        2  대중적인 화이트 러버            1
284  12.0   2   3   2        2  대중적인 화이트 러버            1
67   12.0   2   3   3        2  대중적인 화이트 러버            1
198  12.0   1   3   3        3  대중적인 화이트 러버            1
56   12.0   1   3   4        3  대중적인 화이트 러버            1
313  12.0   1   4   2        3  대중적인 화이트 러버            1
315  12.0   1   4   3        3  대중적인 화이트 러버            1
298  13.0   1   3   2        2  대중적인 화이트 러버            1
1    13.0   1   3   3        2  대중적인 화이트 러버            1
4    13.0   1   3   4        2  대중적인 화이트 러버            1
258  13.0   1   3   5        2  대중적인 화이트 러버            1
276  13.0   1   4   2        2  대중적인 화이트 러버            1
291  13.0   1   4   3        2  대중적인 화이트 러버            1
282  13.0   2   3   2        2  대중적인 화이트 러버            1
321  13.0   2   3   4        2  대중적인 화이트 러버            1
53   13.0   1   3   3        3  대중적인 화이트 러버            1
294  14.0   1   3   2        2  대중적인 화이트 러버            1
19   14.0   1   3   3        2  대중적인 화이트 러버            1
51   14.0   1   3   4        2  대중적인 화이트 러버            1
274  14.0   2   4   3        2  대중적인 화이트 러버            1
256  15.0   1   3   4        2  대중적인 화이트 러버            1

(9.0, 2, 3, 4, 3, '대중적인 화이트 러버', 1): 1개
(10.0, 1, 4, 3, 2, '대중적인 화이트 러버', 1): 1개
(10.0, 2, 3, 3, 2, '대중적인 화이트 러버', 1): 1개
(10.0, 1, 3, 3, 3, '대중적인 화이트 러버', 1): 1개
(10.0, 2, 3, 3, 3, '대중적인 화이트 러버', 1): 2개
(11.0, 1, 3, 4, 2, '대중적인 화이트 러버', 1): 1개
(11.0, 2, 3, 4, 2, '대중적인 화이트 러버', 1): 1개
(11.0, 2, 3, 3, 3, '대중적인 화이트 러버', 1): 2개
(12.0, 1, 3, 3, 2, '대중적인 화이트 러버', 1): 7개
(12.0, 1, 3, 4, 2, '대중적인 화이트 러버', 1): 2개
(12.0, 1, 4, 2, 2, '대중적인 화이트 러버', 1): 1개
(12.0, 2, 3, 2, 2, '대중적인 화이트 러버', 1): 1개
(12.0, 2, 3, 3, 2, '대중적인 화이트 러버', 1): 3개
(12.0, 1, 3, 3, 3, '대중적인 화이트 러버', 1): 2개
(12.0, 1, 3, 4, 3, '대중적인 화이트 러버', 1): 8개
(12.0, 1, 4, 2, 3, '대중적인 화이트 러버', 1): 1개
(12.0, 1, 4, 3, 3, '대중적인 화이트 러버', 1): 1개
(13.0, 1, 3, 2, 2, '대중적인 화이트 러버', 1): 1개
(13.0, 1, 3, 3, 2, '대중적인 화이트 러버', 1): 27개
(13.0, 1, 3, 4, 2, '대중적인 화이트 러버', 1): 5개
(13.0, 1, 3, 5, 2, '대중적인 화이트 러버', 1): 1개
(13.0, 1, 4, 2, 2, '대중적인 화이트 러버', 1): 1개
(13.0, 1, 4, 3, 2, '대중적인 화이트 러버', 1): 1개
(13.0, 2, 3, 2, 2, '대중적인 화이트 러버', 1): 2개
(13.0, 2, 3, 4, 2, '대중적인 화이트 러버', 1): 1개
(13.0, 1, 3, 3, 3, '대중적인 화이트 러버', 1): 1개
(14.0, 1, 3, 2, 2, '대중적인 화이트 러버', 1): 2개
(14.0, 1, 3, 3, 2, '대중적인 화이트 러버', 1): 8개
(14.0, 1, 3, 4, 2, '대중적인 화이트 러버', 1): 4개
(14.0, 2, 4, 3, 2, '대중적인 화이트 러버', 1): 1개
(15.0, 1, 3, 4, 2, '대중적인 화이트 러버', 1): 1개

       도수  당도  산도  바디  타입_cate           추천솔루션 군집화  추천솔루션 군집화_n
14    6.0   4   3   3        1  숨은 고수인 척하는 당뇨병 술청년            2
16    6.0   5   3   3        1  숨은 고수인 척하는 당뇨병 술청년            2
86    7.0   3   3   5        1  숨은 고수인 척하는 당뇨병 술청년            2
81   12.0   3   2   3        1  숨은 고수인 척하는 당뇨병 술청년            2
85   14.0   3   3   4        1  숨은 고수인 척하는 당뇨병 술청년            2
83   14.0   3   3   5        1  숨은 고수인 척하는 당뇨병 술청년            2
205  15.0   5   3   5        1  숨은 고수인 척하는 당뇨병 술청년            2

(6.0, 4, 3, 3, 1, '숨은 고수인 척하는 당뇨병 술청년', 2): 1개
(6.0, 5, 3, 3, 1, '숨은 고수인 척하는 당뇨병 술청년', 2): 1개
(7.0, 3, 3, 5, 1, '숨은 고수인 척하는 당뇨병 술청년', 2): 1개
(12.0, 3, 2, 3, 1, '숨은 고수인 척하는 당뇨병 술청년', 2): 1개
(14.0, 3, 3, 4, 1, '숨은 고수인 척하는 당뇨병 술청년', 2): 1개
(14.0, 3, 3, 5, 1, '숨은 고수인 척하는 당뇨병 술청년', 2): 2개
(15.0, 5, 3, 5, 1, '숨은 고수인 척하는 당뇨병 술청년', 2): 1개

       도수  당도  산도  바디  타입_cate    추천솔루션 군집화  추천솔루션 군집화_n
278   8.0   4   4   3        2  당뇨병 화이트 술청년            3
80    8.0   5   2   5        2  당뇨병 화이트 술청년            3
75    8.0   5   3   3        2  당뇨병 화이트 술청년            3
77    8.0   5   3   4        2  당뇨병 화이트 술청년            3
68    9.0   4   3   3        2  당뇨병 화이트 술청년            3
155   9.0   5   3   2        2  당뇨병 화이트 술청년            3
78   10.0   4   3   4        2  당뇨병 화이트 술청년            3
79   10.0   5   2   4        2  당뇨병 화이트 술청년            3
287  10.0   5   3   4        2  당뇨병 화이트 술청년            3
122  11.0   5   3   4        2  당뇨병 화이트 술청년            3
121  12.0   4   3   2        2  당뇨병 화이트 술청년            3
119  12.0   4   3   3        2  당뇨병 화이트 술청년            3
124  12.0   5   3   4        2  당뇨병 화이트 술청년            3
279  12.0   5   4   4        2  당뇨병 화이트 술청년            3
283  13.0   3   3   2        2  당뇨병 화이트 술청년            3
120  13.0   3   3   3        2  당뇨병 화이트 술청년            3
15   13.0   5   3   2        2  당뇨병 화이트 술청년            3
202  13.0   5   3   4        2  당뇨병 화이트 술청년            3

(8.0, 4, 4, 3, 2, '당뇨병 화이트 술청년', 3): 1개
(8.0, 5, 2, 5, 2, '당뇨병 화이트 술청년', 3): 1개
(8.0, 5, 3, 3, 2, '당뇨병 화이트 술청년', 3): 1개
(8.0, 5, 3, 4, 2, '당뇨병 화이트 술청년', 3): 1개
(9.0, 4, 3, 3, 2, '당뇨병 화이트 술청년', 3): 2개
(9.0, 5, 3, 2, 2, '당뇨병 화이트 술청년', 3): 1개
(10.0, 4, 3, 4, 2, '당뇨병 화이트 술청년', 3): 1개
(10.0, 5, 2, 4, 2, '당뇨병 화이트 술청년', 3): 1개
(10.0, 5, 3, 4, 2, '당뇨병 화이트 술청년', 3): 1개
(11.0, 5, 3, 4, 2, '당뇨병 화이트 술청년', 3): 1개
(12.0, 4, 3, 2, 2, '당뇨병 화이트 술청년', 3): 2개
(12.0, 4, 3, 3, 2, '당뇨병 화이트 술청년', 3): 2개
(12.0, 5, 3, 4, 2, '당뇨병 화이트 술청년', 3): 2개
(12.0, 5, 4, 4, 2, '당뇨병 화이트 술청년', 3): 1개
(13.0, 3, 3, 2, 2, '당뇨병 화이트 술청년', 3): 2개
(13.0, 3, 3, 3, 2, '당뇨병 화이트 술청년', 3): 1개
(13.0, 5, 3, 2, 2, '당뇨병 화이트 술청년', 3): 3개
(13.0, 5, 3, 4, 2, '당뇨병 화이트 술청년', 3): 1개

      도수  당도  산도  바디  타입_cate  추천솔루션 군집화  추천솔루션 군집화_n
96   1.0   1   3   4        1  숨은 고수 술린이            4
163  1.0   1   3   3        2  숨은 고수 술린이            4
32   1.0   1   3   4        2  숨은 고수 술린이            4
89   7.0   1   3   4        1  숨은 고수 술린이            4
87   7.0   1   3   5        1  숨은 고수 술린이            4
88   7.0   1   3   3        2  숨은 고수 술린이            4

(1.0, 1, 3, 4, 1, '숨은 고수 술린이', 4): 9개
(1.0, 1, 3, 3, 2, '숨은 고수 술린이', 4): 1개
(1.0, 1, 3, 4, 2, '숨은 고수 술린이', 4): 5개
(7.0, 1, 3, 4, 1, '숨은 고수 술린이', 4): 2개
(7.0, 1, 3, 5, 1, '숨은 고수 술린이', 4): 1개
(7.0, 1, 3, 3, 2, '숨은 고수 술린이', 4): 2개

      도수  당도  산도  바디  타입_cate     추천솔루션 군집화  추천솔루션 군집화_n
154  5.0   5   3   2        2  대중없는 당뇨병 술청년            5
197  5.0   4   3   3        3  대중없는 당뇨병 술청년            5
172  5.0   5   3   4        3  대중없는 당뇨병 술청년            5
128  7.0   4   3   3        3  대중없는 당뇨병 술청년            5
137  7.0   5   3   4        3  대중없는 당뇨병 술청년            5
306  7.0   5   3   5        3  대중없는 당뇨병 술청년            5
173  9.0   5   3   4        3  대중없는 당뇨병 술청년            5

(5.0, 5, 3, 2, 2, '대중없는 당뇨병 술청년', 5): 2개
(5.0, 4, 3, 3, 3, '대중없는 당뇨병 술청년', 5): 1개
(5.0, 5, 3, 4, 3, '대중없는 당뇨병 술청년', 5): 1개
(7.0, 4, 3, 3, 3, '대중없는 당뇨병 술청년', 5): 2개
(7.0, 5, 3, 4, 3, '대중없는 당뇨병 술청년', 5): 1개
(7.0, 5, 3, 5, 3, '대중없는 당뇨병 술청년', 5): 1개
(9.0, 5, 3, 4, 3, '대중없는 당뇨병 술청년', 5): 1개

       도수  당도  산도  바디  타입_cate           추천솔루션 군집화  추천솔루션 군집화_n
236  16.0   1   3   5        1  올~ 쎈데! 술부심 쌉가능 술른이            6
304  17.0   2   2   4        1  올~ 쎈데! 술부심 쌉가능 술른이            6

(16.0, 1, 3, 5, 1, '올~ 쎈데! 술부심 쌉가능 술른이', 6): 1개
(17.0, 2, 2, 4, 1, '올~ 쎈데! 술부심 쌉가능 술른이', 6): 2개

#### 의사결정 트리 분류모델

In [114]:
wine_df_model = wine_df[['와인이름','도수', '당도', '산도', '바디','타입_cate','추천솔루션 군집화', '추천솔루션 군집화_n']]
wine_df_model

                     와인이름    도수  당도  산도  바디  타입_cate    추천솔루션 군집화  추천솔루션 군집화_n
0           이기갈 꼬뜨 뒤 론 레드  13.0   1   2   4        1    대중적인 레드러버            0
1          이기갈 꼬뜨 뒤 론 화이트  13.0   1   3   3        2  대중적인 화이트 러버            1
2    이기갈 꼬뜨 로띠 ‘브륀 & 블롱드’  13.0   1   3   5        1    대중적인 레드러버            0
3       이기갈 꼬뜨 로띠 ‘샤또 당퓌’  13.0   1   3   5        1    대중적인 레드러버            0
4                이기갈 꽁드리유  13.0   1   3   4        2  대중적인 화이트 러버            1
..                    ...   ...  ..  ..  ..      ...          ...          ...
320        까테나 자파타 까테나 말벡  14.0   1   3   3        1    대중적인 레드러버            0
321   까테나 자파타 까테나 알타 샤르도네  13.0   2   3   4        2  대중적인 화이트 러버            1
322     까테나 자파타 까테나 알타 말벡  14.0   1   3   4        1    대중적인 레드러버            0
323       까테나 자파타 니카시아 말벡  14.0   1   3   5        1    대중적인 레드러버            0
324      까테나 자파타 아르헨티노 말벡  14.0   1   4   5        1    대중적인 레드러버            0

[325 rows x 8 columns]

In [115]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

x = wine_df_model.drop(columns = ['와인이름','추천솔루션 군집화','추천솔루션 군집화_n'])
y = wine_df_model['추천솔루션 군집화_n']

dtree = DecisionTreeClassifier()

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 5)
dtree.fit(X_train, y_train)
pred = dtree.predict(X_test)

accuracy_score(y_test, pred)

1.0

In [116]:
# 모델 파일 저장

import pickle
import joblib

filename = 'wine_model.pkl'
joblib.dump(dtree, filename)

['wine_model.pkl']

In [117]:
# 파일 불러오기: 객체가 나올 것

mdl = joblib.load('wine_model.pkl')
mdl

DecisionTreeClassifier()

In [118]:
# 모델 확인

data = [16.0, 1, 3, 4, 2]

db_df = pd.DataFrame(columns = ['도수', '당도', '산도', '바디', '타입_cate'])
db_df.loc[0] = data
y_pred = mdl.predict(db_df)

y_pred[0]

1

In [119]:
# 피처별 중요도
frame = pd.DataFrame(columns = ['도수', '당도', '산도', '바디', '타입_cate'])
importance = pd.DataFrame(np.round(dtree.feature_importances_, 3))
pd.concat([frame, importance.transpose().rename(columns = {0: '도수',
                                                           1: '당도',
                                                           2: '산도',
                                                           3: '바디',
                                                           4: '타입_cate'})], axis = 0)

      도수     당도   산도   바디 타입_cate
0  0.276  0.253  0.0  0.0   0.471

In [120]:
wine_df[['추천솔루션 군집화','추천솔루션 군집화_n']].value_counts()

추천솔루션 군집화           추천솔루션 군집화_n
대중적인 레드러버           0              168
대중적인 화이트 러버         1               92
당뇨병 화이트 술청년         3               25
숨은 고수 술린이           4               20
대중없는 당뇨병 술청년        5                9
숨은 고수인 척하는 당뇨병 술청년  2                8
올~ 쎈데! 술부심 쌉가능 술른이  6                3
dtype: int64

### (재군집) 분류모델링__ 도수 연속형

In [121]:
import pandas as pd


wine_df = pd.read_csv('wine_df_final_clustering_v2.csv', index_col = 0)
wine_df.head()

,와인이름,영어이름,와인타입,"나라, 와이너리",포도종,도수,당도,산도,바디,탄닌,...,도수_cate2,당도_cate2,산도_cate2,바디_cate2,타입_cate2,대표 중분류 아로마1,대표 중분류 아로마2,추천솔루션 군집화,상황별추천 군집화,상황별추천 군집화_n
0,이기갈 꼬뜨 뒤 론 레드,E.Guigal Cotes du Rhone Rouge,레드 와인,프랑스 > 론 / 이 기갈,"시라 49%, 그르나쉬 48%, 무르베드르 3%",13.0,1,2,4,1.0,...,적당함,달지 않음,적당함,끈적임,레드,빨간 과일,허베이셔스,어른입맛 RED 술청년,가족과 함께,0
1,이기갈 꼬뜨 뒤 론 화이트,E.Guigal Cotes du Rhone Blanc,화이트 와인,프랑스 > 론 / 이 기갈,"비오니에 70%, 루산느 10%, 마르산느 9%, 끌레레뜨 8%, 부르불랑 3%",13.0,1,3,3,NaN,...,적당함,달지 않음,신맛,적당함,화이트,꽃,핵과,어른입맛 WHITE 술청년,가족과 함께,0
2,이기갈 꼬뜨 로띠 ‘브륀 & 블롱드’,E.Guigal Cot-Rotie ‘Brune & Blonde de Guigal’,레드 와인,프랑스 > 론 / 이 기갈,"시라 96%, 비오니에 4%",13.0,1,3,5,1.0,...,적당함,달지 않음,신맛,끈적임,레드,자연(Earthy),오크(Oak),어른입맛 RED 술청년,가족과 함께,0
3,이기갈 꼬뜨 로띠 ‘샤또 당퓌’,E.Guigal Cote-Rotie ‘Chateau d’Ampuis’,레드 와인,프랑스 > 론 / 이 기갈,"시라 93%, 비오니에 7%",13.0,1,3,5,1.0,...,적당함,달지 않음,신맛,끈적임,레드,오크(Oak),녹색 과일,어른입맛 RED 술청년,가족과 함께,0
4,이기갈 꽁드리유,E.Guigal Condrieu,화이트 와인,프랑스 > 론 / 이 기갈,비오니에 100%,13.0,1,3,4,NaN,...,적당함,달지 않음,신맛,끈적임,화이트,핵과,NaN,어른입맛 WHITE 술청년,가족과 함께,0

In [122]:
wine_df.columns

Index(['와인이름', '영어이름', '와인타입', '나라, 와이너리', '포도종', '도수', '당도', '산도', '바디', '탄닌',
       '와이너리이름', '와이너리설명', '와이너리특징', '아로마 딕셔너리', '곁들일 음식', '음식', '아로마 중분류',
       '아로마 소분류', '대표 중분류 아로마', '도수_cate', '당도_cate', '산도_cate', '바디_cate',
       '타입_cate', '도수_cate2', '당도_cate2', '산도_cate2', '바디_cate2', '타입_cate2',
       '대표 중분류 아로마1', '대표 중분류 아로마2', '추천솔루션 군집화', '상황별추천 군집화', '상황별추천 군집화_n'],
      dtype='object')

In [123]:
import numpy as np
wine_df['추천솔루션 군집화_n'] = np.nan

for i, clu in enumerate(wine_df['추천솔루션 군집화'].unique()):
    wine_df.loc[wine_df['추천솔루션 군집화'] == clu, '추천솔루션 군집화_n'] = i
    
wine_df['추천솔루션 군집화_n'] = wine_df['추천솔루션 군집화_n'].astype(int)
wine_df

,와인이름,영어이름,와인타입,"나라, 와이너리",포도종,도수,당도,산도,바디,탄닌,...,당도_cate2,산도_cate2,바디_cate2,타입_cate2,대표 중분류 아로마1,대표 중분류 아로마2,추천솔루션 군집화,상황별추천 군집화,상황별추천 군집화_n,추천솔루션 군집화_n
0,이기갈 꼬뜨 뒤 론 레드,E.Guigal Cotes du Rhone Rouge,레드 와인,프랑스 > 론 / 이 기갈,"시라 49%, 그르나쉬 48%, 무르베드르 3%",13.0,1,2,4,1.0,...,달지 않음,적당함,끈적임,레드,빨간 과일,허베이셔스,어른입맛 RED 술청년,가족과 함께,0,0
1,이기갈 꼬뜨 뒤 론 화이트,E.Guigal Cotes du Rhone Blanc,화이트 와인,프랑스 > 론 / 이 기갈,"비오니에 70%, 루산느 10%, 마르산느 9%, 끌레레뜨 8%, 부르불랑 3%",13.0,1,3,3,NaN,...,달지 않음,신맛,적당함,화이트,꽃,핵과,어른입맛 WHITE 술청년,가족과 함께,0,1
2,이기갈 꼬뜨 로띠 ‘브륀 & 블롱드’,E.Guigal Cot-Rotie ‘Brune & Blonde de Guigal’,레드 와인,프랑스 > 론 / 이 기갈,"시라 96%, 비오니에 4%",13.0,1,3,5,1.0,...,달지 않음,신맛,끈적임,레드,자연(Earthy),오크(Oak),어른입맛 RED 술청년,가족과 함께,0,0
3,이기갈 꼬뜨 로띠 ‘샤또 당퓌’,E.Guigal Cote-Rotie ‘Chateau d’Ampuis’,레드 와인,프랑스 > 론 / 이 기갈,"시라 93%, 비오니에 7%",13.0,1,3,5,1.0,...,달지 않음,신맛,끈적임,레드,오크(Oak),녹색 과일,어른입맛 RED 술청년,가족과 함께,0,0
4,이기갈 꽁드리유,E.Guigal Condrieu,화이트 와인,프랑스 > 론 / 이 기갈,비오니에 100%,13.0,1,3,4,NaN,...,달지 않음,신맛,끈적임,화이트,핵과,NaN,어른입맛 WHITE 술청년,가족과 함께,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
320,까테나 자파타 까테나 말벡,Catena Zapata Catena Malbec,레드 와인,아르헨티나 > 멘도자 / 까테나 자파타,말백 100%,14.0,1,3,3,1.0,...,달지 않음,신맛,적당함,레드,자연(Earthy),오크(Oak),어른입맛 RED 술청년,술른이 연인과함께,3,0
321,까테나 자파타 까테나 알타 샤르도네,Catena Zapata Catena Alta Chardonnay,화이트 와인,아르헨티나 > 멘도자 / 까테나 자파타,샤르도네 100%,13.0,2,3,4,NaN,...,달지 않음,신맛,끈적임,화이트,자연(Earthy),녹색 과일,어른입맛 WHITE 술청년,가족과 함께,0,1
322,까테나 자파타 까테나 알타 말벡,Catena Zapata Catena Alta Malbec,레드 와인,아르헨티나 > 멘도자 / 까테나 자파타,말백 100%,14.0,1,3,4,1.0,...,달지 않음,신맛,끈적임,레드,오크(Oak),빨간 과일,어른입맛 RED 술청년,술른이 연인과함께,3,0
323,까테나 자파타 니카시아 말벡,Catena Zapata Nicasia Malbec,레드 와인,아르헨티나 > 멘도자 / 까테나 자파타,말벡 100%,14.0,1,3,5,1.0,...,달지 않음,신맛,끈적임,레드,오크(Oak),꽃,어른입맛 RED 술청년,술른이 연인과함께,3,0
324,까테나 자파타 아르헨티노 말벡,Catena Zapata Argentino Malbec,레드 와인,아르헨티나 > 멘도자 / 까테나 자파타,말벡 100%,14.0,1,4,5,1.0,...,달지 않음,신맛,끈적임,레드,녹색 과일,빨간 과일,어른입맛 RED 술청년,술른이 연인과함께,3,0

In [124]:
wine_df[['추천솔루션 군집화','추천솔루션 군집화_n']].value_counts()

추천솔루션 군집화        추천솔루션 군집화_n
어른입맛 RED 술청년     0              168
어른입맛 WHITE 술청년   1               92
어린이입맛 WHITE 술청년  3               25
어린이입맛 술린이        2               23
어른입맛 술린이         4                9
어린이입맛 RED 술청년    5                5
어른입맛 RED 술른이     6                3
dtype: int64

#### 군집별 데이터(중복제거) 확인

In [125]:
wine_df_model = wine_df[['와인이름','도수', '당도', '산도', '바디','타입_cate','추천솔루션 군집화', '추천솔루션 군집화_n']]
wine_df_model

,와인이름,도수,당도,산도,바디,타입_cate,추천솔루션 군집화,추천솔루션 군집화_n
0,이기갈 꼬뜨 뒤 론 레드,13.0,1,2,4,1,어른입맛 RED 술청년,0
1,이기갈 꼬뜨 뒤 론 화이트,13.0,1,3,3,2,어른입맛 WHITE 술청년,1
2,이기갈 꼬뜨 로띠 ‘브륀 & 블롱드’,13.0,1,3,5,1,어른입맛 RED 술청년,0
3,이기갈 꼬뜨 로띠 ‘샤또 당퓌’,13.0,1,3,5,1,어른입맛 RED 술청년,0
4,이기갈 꽁드리유,13.0,1,3,4,2,어른입맛 WHITE 술청년,1
...,...,...,...,...,...,...,...,...
320,까테나 자파타 까테나 말벡,14.0,1,3,3,1,어른입맛 RED 술청년,0
321,까테나 자파타 까테나 알타 샤르도네,13.0,2,3,4,2,어른입맛 WHITE 술청년,1
322,까테나 자파타 까테나 알타 말벡,14.0,1,3,4,1,어른입맛 RED 술청년,0
323,까테나 자파타 니카시아 말벡,14.0,1,3,5,1,어른입맛 RED 술청년,0
324,까테나 자파타 아르헨티노 말벡,14.0,1,4,5,1,어른입맛 RED 술청년,0

In [126]:
wine_df_model_test = wine_df_model.drop(columns = ['와인이름'])
for i in range(7):
    df = wine_df_model_test[wine_df_model_test['추천솔루션 군집화_n'] == i].drop_duplicates()
    df = df.sort_values(['도수','타입_cate','당도','산도','바디'])
    display(df)

       도수  당도  산도  바디  타입_cate      추천솔루션 군집화  추천솔루션 군집화_n
9    12.0   1   3   4        1  어른입맛 RED 술청년             0
6    12.0   1   3   5        1  어른입맛 RED 술청년             0
290  13.0   1   2   3        1  어른입맛 RED 술청년             0
0    13.0   1   2   4        1  어른입맛 RED 술청년             0
312  13.0   1   3   3        1  어른입맛 RED 술청년             0
5    13.0   1   3   4        1  어른입맛 RED 술청년             0
2    13.0   1   3   5        1  어른입맛 RED 술청년             0
64   13.0   2   3   4        1  어른입맛 RED 술청년             0
254  14.0   1   1   4        1  어른입맛 RED 술청년             0
295  14.0   1   2   4        1  어른입맛 RED 술청년             0
318  14.0   1   3   3        1  어른입맛 RED 술청년             0
18   14.0   1   3   4        1  어른입맛 RED 술청년             0
10   14.0   1   3   5        1  어른입맛 RED 술청년             0
324  14.0   1   4   5        1  어른입맛 RED 술청년             0
303  14.0   2   2   4        1  어른입맛 RED 술청년             0
301  14.0   2   3   4        1  어른입맛 RED 술청년             0
292  15.0   1   2   4        1  어른입맛 RED 술청년             0
69   15.0   1   3   4        1  어른입맛 RED 술청년             0
107  15.0   1   3   5        1  어른입맛 RED 술청년             0

       도수  당도  산도  바디  타입_cate       추천솔루션 군집화  추천솔루션 군집화_n
66    9.0   2   3   4        3  어른입맛 WHITE 술청년            1
277  10.0   1   4   3        2  어른입맛 WHITE 술청년            1
76   10.0   2   3   3        2  어른입맛 WHITE 술청년            1
52   10.0   1   3   3        3  어른입맛 WHITE 술청년            1
111  10.0   2   3   3        3  어른입맛 WHITE 술청년            1
26   11.0   1   3   4        2  어른입맛 WHITE 술청년            1
238  11.0   2   3   4        2  어른입맛 WHITE 술청년            1
92   11.0   2   3   3        3  어른입맛 WHITE 술청년            1
135  12.0   1   3   3        2  어른입맛 WHITE 술청년            1
24   12.0   1   3   4        2  어른입맛 WHITE 술청년            1
307  12.0   1   4   2        2  어른입맛 WHITE 술청년            1
284  12.0   2   3   2        2  어른입맛 WHITE 술청년            1
67   12.0   2   3   3        2  어른입맛 WHITE 술청년            1
198  12.0   1   3   3        3  어른입맛 WHITE 술청년            1
56   12.0   1   3   4        3  어른입맛 WHITE 술청년            1
313  12.0   1   4   2        3  어른입맛 WHITE 술청년            1
315  12.0   1   4   3        3  어른입맛 WHITE 술청년            1
298  13.0   1   3   2        2  어른입맛 WHITE 술청년            1
1    13.0   1   3   3        2  어른입맛 WHITE 술청년            1
4    13.0   1   3   4        2  어른입맛 WHITE 술청년            1
258  13.0   1   3   5        2  어른입맛 WHITE 술청년            1
276  13.0   1   4   2        2  어른입맛 WHITE 술청년            1
291  13.0   1   4   3        2  어른입맛 WHITE 술청년            1
282  13.0   2   3   2        2  어른입맛 WHITE 술청년            1
321  13.0   2   3   4        2  어른입맛 WHITE 술청년            1
53   13.0   1   3   3        3  어른입맛 WHITE 술청년            1
294  14.0   1   3   2        2  어른입맛 WHITE 술청년            1
19   14.0   1   3   3        2  어른입맛 WHITE 술청년            1
51   14.0   1   3   4        2  어른입맛 WHITE 술청년            1
274  14.0   2   4   3        2  어른입맛 WHITE 술청년            1
256  15.0   1   3   4        2  어른입맛 WHITE 술청년            1

      도수  당도  산도  바디  타입_cate  추천솔루션 군집화  추천솔루션 군집화_n
96   1.0   1   3   4        1  어린이입맛 술린이            2
154  5.0   5   3   2        2  어린이입맛 술린이            2
197  5.0   4   3   3        3  어린이입맛 술린이            2
172  5.0   5   3   4        3  어린이입맛 술린이            2
14   6.0   4   3   3        1  어린이입맛 술린이            2
16   6.0   5   3   3        1  어린이입맛 술린이            2
89   7.0   1   3   4        1  어린이입맛 술린이            2
87   7.0   1   3   5        1  어린이입맛 술린이            2
128  7.0   4   3   3        3  어린이입맛 술린이            2
137  7.0   5   3   4        3  어린이입맛 술린이            2
306  7.0   5   3   5        3  어린이입맛 술린이            2
173  9.0   5   3   4        3  어린이입맛 술린이            2

       도수  당도  산도  바디  타입_cate        추천솔루션 군집화  추천솔루션 군집화_n
278   8.0   4   4   3        2  어린이입맛 WHITE 술청년            3
80    8.0   5   2   5        2  어린이입맛 WHITE 술청년            3
75    8.0   5   3   3        2  어린이입맛 WHITE 술청년            3
77    8.0   5   3   4        2  어린이입맛 WHITE 술청년            3
68    9.0   4   3   3        2  어린이입맛 WHITE 술청년            3
155   9.0   5   3   2        2  어린이입맛 WHITE 술청년            3
78   10.0   4   3   4        2  어린이입맛 WHITE 술청년            3
79   10.0   5   2   4        2  어린이입맛 WHITE 술청년            3
287  10.0   5   3   4        2  어린이입맛 WHITE 술청년            3
122  11.0   5   3   4        2  어린이입맛 WHITE 술청년            3
121  12.0   4   3   2        2  어린이입맛 WHITE 술청년            3
119  12.0   4   3   3        2  어린이입맛 WHITE 술청년            3
124  12.0   5   3   4        2  어린이입맛 WHITE 술청년            3
279  12.0   5   4   4        2  어린이입맛 WHITE 술청년            3
283  13.0   3   3   2        2  어린이입맛 WHITE 술청년            3
120  13.0   3   3   3        2  어린이입맛 WHITE 술청년            3
15   13.0   5   3   2        2  어린이입맛 WHITE 술청년            3
202  13.0   5   3   4        2  어린이입맛 WHITE 술청년            3

      도수  당도  산도  바디  타입_cate 추천솔루션 군집화  추천솔루션 군집화_n
163  1.0   1   3   3        2  어른입맛 술린이            4
32   1.0   1   3   4        2  어른입맛 술린이            4
86   7.0   3   3   5        1  어른입맛 술린이            4
88   7.0   1   3   3        2  어른입맛 술린이            4

       도수  당도  산도  바디  타입_cate      추천솔루션 군집화  추천솔루션 군집화_n
81   12.0   3   2   3        1  어린이입맛 RED 술청년            5
85   14.0   3   3   4        1  어린이입맛 RED 술청년            5
83   14.0   3   3   5        1  어린이입맛 RED 술청년            5
205  15.0   5   3   5        1  어린이입맛 RED 술청년            5

       도수  당도  산도  바디  타입_cate      추천솔루션 군집화  추천솔루션 군집화_n
236  16.0   1   3   5        1  어른입맛 RED 술른이             6
304  17.0   2   2   4        1  어른입맛 RED 술른이             6

#### 데이터 군집화 수정

도수	당도	산도	바디	타입_cate	
1.0	1	3	4	1	어린이입맛 술린이	2  -> 어른입맛 술린이, 4 <br>
7.0	1	3	4	1	어린이입맛 술린이	2 -> 어른입맛 술린이, 4 	
7.0	1	3	5	1	어린이입맛 술린이	2  -> 어른입맛 술린이, 4

7.0	3	3	5	1	어른입맛 술린이  4 -> 어린이입맛 술린이, 2


9.0	5	3	4	3	어린이입맛 술린이	2 -> 어린이입맛 WHITE 술청년

In [145]:
# 해당 내용 수정
##1
li = [[1.0, 1, 3, 4, 1],[7.0, 1, 3, 4, 1],[7.0, 1, 3, 5, 1]]

for al, sw, ac, bo, ty in li: 
    wine_df.loc[(wine_df['도수'] == al) & (wine_df['당도'] == sw) & (wine_df['산도'] == ac) & \
                (wine_df['바디'] == bo) &  (wine_df['타입_cate'] == ty), '추천솔루션 군집화' ] = '어른입맛 술린이'
    wine_df.loc[(wine_df['도수'] == al) & (wine_df['당도'] == sw) & (wine_df['산도'] == ac) & \
                (wine_df['바디'] == bo) &  (wine_df['타입_cate'] == ty), '추천솔루션 군집화_n' ] = 4
##2
wine_df.loc[(wine_df['도수'] == 7.0) & (wine_df['당도'] == 3) & (wine_df['산도'] == 3) & \
            (wine_df['바디'] == 5) &  (wine_df['타입_cate'] == 1), '추천솔루션 군집화' ] = '어린이입맛 술린이'

wine_df.loc[(wine_df['도수'] == 7.0) & (wine_df['당도'] == 3) & (wine_df['산도'] == 3) & \
            (wine_df['바디'] == 5) &  (wine_df['타입_cate'] == 1), '추천솔루션 군집화_n' ] = 2

##3
wine_df.loc[(wine_df['도수'] == 9.0) & (wine_df['당도'] == 5) & (wine_df['산도'] == 3) & \
            (wine_df['바디'] == 4) &  (wine_df['타입_cate'] == 3), '추천솔루션 군집화' ] = '어린이입맛 WHITE 술청년'

##3
wine_df.loc[(wine_df['도수'] == 9.0) & (wine_df['당도'] == 5) & (wine_df['산도'] == 3) & \
            (wine_df['바디'] == 4) &  (wine_df['타입_cate'] == 3), '추천솔루션 군집화_n' ] = 3

In [146]:
df.reset_index().loc[idx]

index                    304
도수                      17.0
당도                         2
산도                         2
바디                         4
타입_cate                    1
추천솔루션 군집화      어른입맛 RED 술른이
추천솔루션 군집화_n                6
Name: 1, dtype: object

In [147]:
# 확인

wine_df_model = wine_df[['와인이름','도수', '당도', '산도', '바디','타입_cate','추천솔루션 군집화', '추천솔루션 군집화_n']]
wine_df_model_test = wine_df_model.drop(columns = ['와인이름'])
for i in range(7):
    df = wine_df_model_test[wine_df_model_test['추천솔루션 군집화_n'] == i].drop_duplicates()
    df = df.sort_values(['도수','타입_cate','당도','산도','바디'])
    display(df)
    for idx in range(len(df)):
        i, al, sw, ac, bo, ty, x, xn = df.reset_index().loc[idx]
        leng = len(wine_df[(wine_df['도수']== al)&
                          (wine_df['당도']== sw)&
                          (wine_df['산도']== ac)&
                          (wine_df['바디']== bo)&
                          (wine_df['타입_cate']== ty)])
        print(f'{al, sw, ac, bo, ty, x, xn}: {leng}개')

       도수  당도  산도  바디  타입_cate      추천솔루션 군집화  추천솔루션 군집화_n
9    12.0   1   3   4        1  어른입맛 RED 술청년             0
6    12.0   1   3   5        1  어른입맛 RED 술청년             0
290  13.0   1   2   3        1  어른입맛 RED 술청년             0
0    13.0   1   2   4        1  어른입맛 RED 술청년             0
312  13.0   1   3   3        1  어른입맛 RED 술청년             0
5    13.0   1   3   4        1  어른입맛 RED 술청년             0
2    13.0   1   3   5        1  어른입맛 RED 술청년             0
64   13.0   2   3   4        1  어른입맛 RED 술청년             0
254  14.0   1   1   4        1  어른입맛 RED 술청년             0
295  14.0   1   2   4        1  어른입맛 RED 술청년             0
318  14.0   1   3   3        1  어른입맛 RED 술청년             0
18   14.0   1   3   4        1  어른입맛 RED 술청년             0
10   14.0   1   3   5        1  어른입맛 RED 술청년             0
324  14.0   1   4   5        1  어른입맛 RED 술청년             0
303  14.0   2   2   4        1  어른입맛 RED 술청년             0
301  14.0   2   3   4        1  어른입맛 RED 술청년             0
292  15.0   1   2   4        1  어른입맛 RED 술청년             0
69   15.0   1   3   4        1  어른입맛 RED 술청년             0
107  15.0   1   3   5        1  어른입맛 RED 술청년             0

(12.0, 1, 3, 4, 1, '어른입맛 RED 술청년 ', 0): 5개
(12.0, 1, 3, 5, 1, '어른입맛 RED 술청년 ', 0): 2개
(13.0, 1, 2, 3, 1, '어른입맛 RED 술청년 ', 0): 1개
(13.0, 1, 2, 4, 1, '어른입맛 RED 술청년 ', 0): 4개
(13.0, 1, 3, 3, 1, '어른입맛 RED 술청년 ', 0): 1개
(13.0, 1, 3, 4, 1, '어른입맛 RED 술청년 ', 0): 53개
(13.0, 1, 3, 5, 1, '어른입맛 RED 술청년 ', 0): 21개
(13.0, 2, 3, 4, 1, '어른입맛 RED 술청년 ', 0): 2개
(14.0, 1, 1, 4, 1, '어른입맛 RED 술청년 ', 0): 1개
(14.0, 1, 2, 4, 1, '어른입맛 RED 술청년 ', 0): 2개
(14.0, 1, 3, 3, 1, '어른입맛 RED 술청년 ', 0): 2개
(14.0, 1, 3, 4, 1, '어른입맛 RED 술청년 ', 0): 10개
(14.0, 1, 3, 5, 1, '어른입맛 RED 술청년 ', 0): 51개
(14.0, 1, 4, 5, 1, '어른입맛 RED 술청년 ', 0): 1개
(14.0, 2, 2, 4, 1, '어른입맛 RED 술청년 ', 0): 1개
(14.0, 2, 3, 4, 1, '어른입맛 RED 술청년 ', 0): 1개
(15.0, 1, 2, 4, 1, '어른입맛 RED 술청년 ', 0): 2개
(15.0, 1, 3, 4, 1, '어른입맛 RED 술청년 ', 0): 1개
(15.0, 1, 3, 5, 1, '어른입맛 RED 술청년 ', 0): 7개

       도수  당도  산도  바디  타입_cate       추천솔루션 군집화  추천솔루션 군집화_n
66    9.0   2   3   4        3  어른입맛 WHITE 술청년            1
277  10.0   1   4   3        2  어른입맛 WHITE 술청년            1
76   10.0   2   3   3        2  어른입맛 WHITE 술청년            1
52   10.0   1   3   3        3  어른입맛 WHITE 술청년            1
111  10.0   2   3   3        3  어른입맛 WHITE 술청년            1
26   11.0   1   3   4        2  어른입맛 WHITE 술청년            1
238  11.0   2   3   4        2  어른입맛 WHITE 술청년            1
92   11.0   2   3   3        3  어른입맛 WHITE 술청년            1
135  12.0   1   3   3        2  어른입맛 WHITE 술청년            1
24   12.0   1   3   4        2  어른입맛 WHITE 술청년            1
307  12.0   1   4   2        2  어른입맛 WHITE 술청년            1
284  12.0   2   3   2        2  어른입맛 WHITE 술청년            1
67   12.0   2   3   3        2  어른입맛 WHITE 술청년            1
198  12.0   1   3   3        3  어른입맛 WHITE 술청년            1
56   12.0   1   3   4        3  어른입맛 WHITE 술청년            1
313  12.0   1   4   2        3  어른입맛 WHITE 술청년            1
315  12.0   1   4   3        3  어른입맛 WHITE 술청년            1
298  13.0   1   3   2        2  어른입맛 WHITE 술청년            1
1    13.0   1   3   3        2  어른입맛 WHITE 술청년            1
4    13.0   1   3   4        2  어른입맛 WHITE 술청년            1
258  13.0   1   3   5        2  어른입맛 WHITE 술청년            1
276  13.0   1   4   2        2  어른입맛 WHITE 술청년            1
291  13.0   1   4   3        2  어른입맛 WHITE 술청년            1
282  13.0   2   3   2        2  어른입맛 WHITE 술청년            1
321  13.0   2   3   4        2  어른입맛 WHITE 술청년            1
53   13.0   1   3   3        3  어른입맛 WHITE 술청년            1
294  14.0   1   3   2        2  어른입맛 WHITE 술청년            1
19   14.0   1   3   3        2  어른입맛 WHITE 술청년            1
51   14.0   1   3   4        2  어른입맛 WHITE 술청년            1
274  14.0   2   4   3        2  어른입맛 WHITE 술청년            1
256  15.0   1   3   4        2  어른입맛 WHITE 술청년            1

(9.0, 2, 3, 4, 3, '어른입맛 WHITE 술청년', 1): 1개
(10.0, 1, 4, 3, 2, '어른입맛 WHITE 술청년', 1): 1개
(10.0, 2, 3, 3, 2, '어른입맛 WHITE 술청년', 1): 1개
(10.0, 1, 3, 3, 3, '어른입맛 WHITE 술청년', 1): 1개
(10.0, 2, 3, 3, 3, '어른입맛 WHITE 술청년', 1): 2개
(11.0, 1, 3, 4, 2, '어른입맛 WHITE 술청년', 1): 1개
(11.0, 2, 3, 4, 2, '어른입맛 WHITE 술청년', 1): 1개
(11.0, 2, 3, 3, 3, '어른입맛 WHITE 술청년', 1): 2개
(12.0, 1, 3, 3, 2, '어른입맛 WHITE 술청년', 1): 7개
(12.0, 1, 3, 4, 2, '어른입맛 WHITE 술청년', 1): 2개
(12.0, 1, 4, 2, 2, '어른입맛 WHITE 술청년', 1): 1개
(12.0, 2, 3, 2, 2, '어른입맛 WHITE 술청년', 1): 1개
(12.0, 2, 3, 3, 2, '어른입맛 WHITE 술청년', 1): 3개
(12.0, 1, 3, 3, 3, '어른입맛 WHITE 술청년', 1): 2개
(12.0, 1, 3, 4, 3, '어른입맛 WHITE 술청년', 1): 8개
(12.0, 1, 4, 2, 3, '어른입맛 WHITE 술청년', 1): 1개
(12.0, 1, 4, 3, 3, '어른입맛 WHITE 술청년', 1): 1개
(13.0, 1, 3, 2, 2, '어른입맛 WHITE 술청년', 1): 1개
(13.0, 1, 3, 3, 2, '어른입맛 WHITE 술청년', 1): 27개
(13.0, 1, 3, 4, 2, '어른입맛 WHITE 술청년', 1): 5개
(13.0, 1, 3, 5, 2, '어른입맛 WHITE 술청년', 1): 1개
(13.0, 1, 4, 2, 2, '어른입맛 WHITE 술청년', 1): 1개
(13.0, 1, 4, 3, 2, '어른입맛 WHITE 술청년', 1): 1개
(13.0, 2, 3, 2, 2, '어른입맛 WHITE 술청년', 1): 2개
(13.0, 2, 3, 4, 2, '어른입맛 WHITE 술청년', 1): 1개
(13.0, 1, 3, 3, 3, '어른입맛 WHITE 술청년', 1): 1개
(14.0, 1, 3, 2, 2, '어른입맛 WHITE 술청년', 1): 2개
(14.0, 1, 3, 3, 2, '어른입맛 WHITE 술청년', 1): 8개
(14.0, 1, 3, 4, 2, '어른입맛 WHITE 술청년', 1): 4개
(14.0, 2, 4, 3, 2, '어른입맛 WHITE 술청년', 1): 1개
(15.0, 1, 3, 4, 2, '어른입맛 WHITE 술청년', 1): 1개

      도수  당도  산도  바디  타입_cate  추천솔루션 군집화  추천솔루션 군집화_n
154  5.0   5   3   2        2  어린이입맛 술린이            2
197  5.0   4   3   3        3  어린이입맛 술린이            2
172  5.0   5   3   4        3  어린이입맛 술린이            2
14   6.0   4   3   3        1  어린이입맛 술린이            2
16   6.0   5   3   3        1  어린이입맛 술린이            2
86   7.0   3   3   5        1  어린이입맛 술린이            2
128  7.0   4   3   3        3  어린이입맛 술린이            2
137  7.0   5   3   4        3  어린이입맛 술린이            2
306  7.0   5   3   5        3  어린이입맛 술린이            2

(5.0, 5, 3, 2, 2, '어린이입맛 술린이', 2): 2개
(5.0, 4, 3, 3, 3, '어린이입맛 술린이', 2): 1개
(5.0, 5, 3, 4, 3, '어린이입맛 술린이', 2): 1개
(6.0, 4, 3, 3, 1, '어린이입맛 술린이', 2): 1개
(6.0, 5, 3, 3, 1, '어린이입맛 술린이', 2): 1개
(7.0, 3, 3, 5, 1, '어린이입맛 술린이', 2): 1개
(7.0, 4, 3, 3, 3, '어린이입맛 술린이', 2): 2개
(7.0, 5, 3, 4, 3, '어린이입맛 술린이', 2): 1개
(7.0, 5, 3, 5, 3, '어린이입맛 술린이', 2): 1개

       도수  당도  산도  바디  타입_cate        추천솔루션 군집화  추천솔루션 군집화_n
278   8.0   4   4   3        2  어린이입맛 WHITE 술청년            3
80    8.0   5   2   5        2  어린이입맛 WHITE 술청년            3
75    8.0   5   3   3        2  어린이입맛 WHITE 술청년            3
77    8.0   5   3   4        2  어린이입맛 WHITE 술청년            3
68    9.0   4   3   3        2  어린이입맛 WHITE 술청년            3
155   9.0   5   3   2        2  어린이입맛 WHITE 술청년            3
173   9.0   5   3   4        3  어린이입맛 WHITE 술청년            3
78   10.0   4   3   4        2  어린이입맛 WHITE 술청년            3
79   10.0   5   2   4        2  어린이입맛 WHITE 술청년            3
287  10.0   5   3   4        2  어린이입맛 WHITE 술청년            3
122  11.0   5   3   4        2  어린이입맛 WHITE 술청년            3
121  12.0   4   3   2        2  어린이입맛 WHITE 술청년            3
119  12.0   4   3   3        2  어린이입맛 WHITE 술청년            3
124  12.0   5   3   4        2  어린이입맛 WHITE 술청년            3
279  12.0   5   4   4        2  어린이입맛 WHITE 술청년            3
283  13.0   3   3   2        2  어린이입맛 WHITE 술청년            3
120  13.0   3   3   3        2  어린이입맛 WHITE 술청년            3
15   13.0   5   3   2        2  어린이입맛 WHITE 술청년            3
202  13.0   5   3   4        2  어린이입맛 WHITE 술청년            3

(8.0, 4, 4, 3, 2, '어린이입맛 WHITE 술청년', 3): 1개
(8.0, 5, 2, 5, 2, '어린이입맛 WHITE 술청년', 3): 1개
(8.0, 5, 3, 3, 2, '어린이입맛 WHITE 술청년', 3): 1개
(8.0, 5, 3, 4, 2, '어린이입맛 WHITE 술청년', 3): 1개
(9.0, 4, 3, 3, 2, '어린이입맛 WHITE 술청년', 3): 2개
(9.0, 5, 3, 2, 2, '어린이입맛 WHITE 술청년', 3): 1개
(9.0, 5, 3, 4, 3, '어린이입맛 WHITE 술청년', 3): 1개
(10.0, 4, 3, 4, 2, '어린이입맛 WHITE 술청년', 3): 1개
(10.0, 5, 2, 4, 2, '어린이입맛 WHITE 술청년', 3): 1개
(10.0, 5, 3, 4, 2, '어린이입맛 WHITE 술청년', 3): 1개
(11.0, 5, 3, 4, 2, '어린이입맛 WHITE 술청년', 3): 1개
(12.0, 4, 3, 2, 2, '어린이입맛 WHITE 술청년', 3): 2개
(12.0, 4, 3, 3, 2, '어린이입맛 WHITE 술청년', 3): 2개
(12.0, 5, 3, 4, 2, '어린이입맛 WHITE 술청년', 3): 2개
(12.0, 5, 4, 4, 2, '어린이입맛 WHITE 술청년', 3): 1개
(13.0, 3, 3, 2, 2, '어린이입맛 WHITE 술청년', 3): 2개
(13.0, 3, 3, 3, 2, '어린이입맛 WHITE 술청년', 3): 1개
(13.0, 5, 3, 2, 2, '어린이입맛 WHITE 술청년', 3): 3개
(13.0, 5, 3, 4, 2, '어린이입맛 WHITE 술청년', 3): 1개

      도수  당도  산도  바디  타입_cate 추천솔루션 군집화  추천솔루션 군집화_n
96   1.0   1   3   4        1  어른입맛 술린이            4
163  1.0   1   3   3        2  어른입맛 술린이            4
32   1.0   1   3   4        2  어른입맛 술린이            4
89   7.0   1   3   4        1  어른입맛 술린이            4
87   7.0   1   3   5        1  어른입맛 술린이            4
88   7.0   1   3   3        2  어른입맛 술린이            4

(1.0, 1, 3, 4, 1, '어른입맛 술린이', 4): 9개
(1.0, 1, 3, 3, 2, '어른입맛 술린이', 4): 1개
(1.0, 1, 3, 4, 2, '어른입맛 술린이', 4): 5개
(7.0, 1, 3, 4, 1, '어른입맛 술린이', 4): 2개
(7.0, 1, 3, 5, 1, '어른입맛 술린이', 4): 1개
(7.0, 1, 3, 3, 2, '어른입맛 술린이', 4): 2개

       도수  당도  산도  바디  타입_cate      추천솔루션 군집화  추천솔루션 군집화_n
81   12.0   3   2   3        1  어린이입맛 RED 술청년            5
85   14.0   3   3   4        1  어린이입맛 RED 술청년            5
83   14.0   3   3   5        1  어린이입맛 RED 술청년            5
205  15.0   5   3   5        1  어린이입맛 RED 술청년            5

(12.0, 3, 2, 3, 1, '어린이입맛 RED 술청년', 5): 1개
(14.0, 3, 3, 4, 1, '어린이입맛 RED 술청년', 5): 1개
(14.0, 3, 3, 5, 1, '어린이입맛 RED 술청년', 5): 2개
(15.0, 5, 3, 5, 1, '어린이입맛 RED 술청년', 5): 1개

       도수  당도  산도  바디  타입_cate      추천솔루션 군집화  추천솔루션 군집화_n
236  16.0   1   3   5        1  어른입맛 RED 술른이             6
304  17.0   2   2   4        1  어른입맛 RED 술른이             6

(16.0, 1, 3, 5, 1, '어른입맛 RED 술른이 ', 6): 1개
(17.0, 2, 2, 4, 1, '어른입맛 RED 술른이 ', 6): 2개

#### 의사결정 트리 분류모델

In [148]:
wine_df_model = wine_df[['와인이름','도수', '당도', '산도', '바디','타입_cate','추천솔루션 군집화', '추천솔루션 군집화_n']]
wine_df_model

,와인이름,도수,당도,산도,바디,타입_cate,추천솔루션 군집화,추천솔루션 군집화_n
0,이기갈 꼬뜨 뒤 론 레드,13.0,1,2,4,1,어른입맛 RED 술청년,0
1,이기갈 꼬뜨 뒤 론 화이트,13.0,1,3,3,2,어른입맛 WHITE 술청년,1
2,이기갈 꼬뜨 로띠 ‘브륀 & 블롱드’,13.0,1,3,5,1,어른입맛 RED 술청년,0
3,이기갈 꼬뜨 로띠 ‘샤또 당퓌’,13.0,1,3,5,1,어른입맛 RED 술청년,0
4,이기갈 꽁드리유,13.0,1,3,4,2,어른입맛 WHITE 술청년,1
...,...,...,...,...,...,...,...,...
320,까테나 자파타 까테나 말벡,14.0,1,3,3,1,어른입맛 RED 술청년,0
321,까테나 자파타 까테나 알타 샤르도네,13.0,2,3,4,2,어른입맛 WHITE 술청년,1
322,까테나 자파타 까테나 알타 말벡,14.0,1,3,4,1,어른입맛 RED 술청년,0
323,까테나 자파타 니카시아 말벡,14.0,1,3,5,1,어른입맛 RED 술청년,0
324,까테나 자파타 아르헨티노 말벡,14.0,1,4,5,1,어른입맛 RED 술청년,0

In [149]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

x = wine_df_model.drop(columns = ['와인이름','추천솔루션 군집화','추천솔루션 군집화_n'])
y = wine_df_model['추천솔루션 군집화_n']

# 학습을 위한 분류모델 객체화
dtree = DecisionTreeClassifier()

# 학습용/테스트용 데이터 분류
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 5)

# 학습
dtree.fit(X_train, y_train)

# 예측
pred = dtree.predict(X_test)

# 평가
accuracy_score(y_test, pred)

1.0

In [150]:
# 학습모델 저장

import pickle
import joblib

filename = 'wine_model_v2.pkl'
joblib.dump(dtree, filename)

['wine_model_v2.pkl']

In [151]:
# 학습된 모델 파일 불러오기

mdl = joblib.load('wine_model_v2.pkl')
mdl

DecisionTreeClassifier()

In [155]:
# 모델링 결과 test

#임의의 도수, 당도, 산도, 바디, 와인타입 지정
data = [7.0, 5, 3, 4, 3]

db_df = pd.DataFrame(columns = ['도수', '당도', '산도', '바디', '타입_cate'])
db_df.loc[0] = data

y_pred = mdl.predict(db_df)

y_pred[0] #어린이입맛 술린이로 예측됨

2

In [156]:
# 피처별 중요도 확인

frame = pd.DataFrame(columns = ['도수', '당도', '산도', '바디', '타입_cate'])

importance = pd.DataFrame(np.round(dtree.feature_importances_, 3))

pd.concat([frame, importance.transpose().rename(columns = {0: '도수',
                                                           1: '당도',
                                                           2: '산도',
                                                           3: '바디',
                                                           4: '타입_cate'})], axis = 0)

      도수     당도   산도   바디 타입_cate
0  0.282  0.258  0.0  0.0    0.46

In [157]:
wine_df[['추천솔루션 군집화','추천솔루션 군집화_n']].value_counts()

추천솔루션 군집화        추천솔루션 군집화_n
어른입맛 RED 술청년     0              168
어른입맛 WHITE 술청년   1               92
어린이입맛 WHITE 술청년  3               26
어른입맛 술린이         4               20
어린이입맛 술린이        2               11
어린이입맛 RED 술청년    5                5
어른입맛 RED 술른이     6                3
dtype: int64

In [159]:
wine_df.to_csv('wine_df_final_clustering_v3데이터일부수정.csv')

### (재군집) 분류모델링__ 도수 범주형

#### 도수 범주화

In [160]:
wine_df_model = wine_df[['와인이름','도수', '당도', '산도', '바디','타입_cate','추천솔루션 군집화', '추천솔루션 군집화_n']]
wine_df_model

,와인이름,도수,당도,산도,바디,타입_cate,추천솔루션 군집화,추천솔루션 군집화_n
0,이기갈 꼬뜨 뒤 론 레드,13.0,1,2,4,1,어른입맛 RED 술청년,0
1,이기갈 꼬뜨 뒤 론 화이트,13.0,1,3,3,2,어른입맛 WHITE 술청년,1
2,이기갈 꼬뜨 로띠 ‘브륀 & 블롱드’,13.0,1,3,5,1,어른입맛 RED 술청년,0
3,이기갈 꼬뜨 로띠 ‘샤또 당퓌’,13.0,1,3,5,1,어른입맛 RED 술청년,0
4,이기갈 꽁드리유,13.0,1,3,4,2,어른입맛 WHITE 술청년,1
...,...,...,...,...,...,...,...,...
320,까테나 자파타 까테나 말벡,14.0,1,3,3,1,어른입맛 RED 술청년,0
321,까테나 자파타 까테나 알타 샤르도네,13.0,2,3,4,2,어른입맛 WHITE 술청년,1
322,까테나 자파타 까테나 알타 말벡,14.0,1,3,4,1,어른입맛 RED 술청년,0
323,까테나 자파타 니카시아 말벡,14.0,1,3,5,1,어른입맛 RED 술청년,0
324,까테나 자파타 아르헨티노 말벡,14.0,1,4,5,1,어른입맛 RED 술청년,0

In [165]:
import warnings
warnings.filterwarnings('ignore')

def dosu_cate2(x):
    y = 0
    if x <= 7.0 : y = 0
    elif x <= 15 : y = 1
    elif x > 15: y = 2
        
    return y

wine_df_model['도수_cate'] = wine_df_model['도수'].apply(lambda x: dosu_cate2(x))

In [166]:
wine_df_model

,와인이름,도수,당도,산도,바디,타입_cate,추천솔루션 군집화,추천솔루션 군집화_n,도수_cate
0,이기갈 꼬뜨 뒤 론 레드,13.0,1,2,4,1,어른입맛 RED 술청년,0,1
1,이기갈 꼬뜨 뒤 론 화이트,13.0,1,3,3,2,어른입맛 WHITE 술청년,1,1
2,이기갈 꼬뜨 로띠 ‘브륀 & 블롱드’,13.0,1,3,5,1,어른입맛 RED 술청년,0,1
3,이기갈 꼬뜨 로띠 ‘샤또 당퓌’,13.0,1,3,5,1,어른입맛 RED 술청년,0,1
4,이기갈 꽁드리유,13.0,1,3,4,2,어른입맛 WHITE 술청년,1,1
...,...,...,...,...,...,...,...,...,...
320,까테나 자파타 까테나 말벡,14.0,1,3,3,1,어른입맛 RED 술청년,0,1
321,까테나 자파타 까테나 알타 샤르도네,13.0,2,3,4,2,어른입맛 WHITE 술청년,1,1
322,까테나 자파타 까테나 알타 말벡,14.0,1,3,4,1,어른입맛 RED 술청년,0,1
323,까테나 자파타 니카시아 말벡,14.0,1,3,5,1,어른입맛 RED 술청년,0,1
324,까테나 자파타 아르헨티노 말벡,14.0,1,4,5,1,어른입맛 RED 술청년,0,1

In [171]:
# 확인
wine_df_model_test = wine_df_model.drop(columns = ['와인이름'])
for i in range(7):
    df = wine_df_model_test[wine_df_model_test['추천솔루션 군집화_n'] == i].drop_duplicates()
    df = df.sort_values(['도수_cate','도수_cate','타입_cate','당도','산도','바디'])
    display(df)
    
    for idx in range(len(df)):

        i, al, sw, ac, bo, ty, x, xn, al_ca  = df.reset_index().loc[idx]
        leng = len(wine_df[(wine_df['도수']== al)&
                          (wine_df['당도']== sw)&
                          (wine_df['산도']== ac)&
                          (wine_df['바디']== bo)&
                          (wine_df['타입_cate']== ty)])
        print(f'{al, sw, ac, bo, ty, x, xn}: {leng}개')

       도수  당도  산도  바디  타입_cate      추천솔루션 군집화  추천솔루션 군집화_n  도수_cate
254  14.0   1   1   4        1  어른입맛 RED 술청년             0        1
290  13.0   1   2   3        1  어른입맛 RED 술청년             0        1
0    13.0   1   2   4        1  어른입맛 RED 술청년             0        1
292  15.0   1   2   4        1  어른입맛 RED 술청년             0        1
295  14.0   1   2   4        1  어른입맛 RED 술청년             0        1
312  13.0   1   3   3        1  어른입맛 RED 술청년             0        1
318  14.0   1   3   3        1  어른입맛 RED 술청년             0        1
5    13.0   1   3   4        1  어른입맛 RED 술청년             0        1
9    12.0   1   3   4        1  어른입맛 RED 술청년             0        1
18   14.0   1   3   4        1  어른입맛 RED 술청년             0        1
69   15.0   1   3   4        1  어른입맛 RED 술청년             0        1
2    13.0   1   3   5        1  어른입맛 RED 술청년             0        1
6    12.0   1   3   5        1  어른입맛 RED 술청년             0        1
10   14.0   1   3   5        1  어른입맛 RED 술청년             0        1
107  15.0   1   3   5        1  어른입맛 RED 술청년             0        1
324  14.0   1   4   5        1  어른입맛 RED 술청년             0        1
303  14.0   2   2   4        1  어른입맛 RED 술청년             0        1
64   13.0   2   3   4        1  어른입맛 RED 술청년             0        1
301  14.0   2   3   4        1  어른입맛 RED 술청년             0        1

(14.0, 1, 1, 4, 1, '어른입맛 RED 술청년 ', 0): 1개
(13.0, 1, 2, 3, 1, '어른입맛 RED 술청년 ', 0): 1개
(13.0, 1, 2, 4, 1, '어른입맛 RED 술청년 ', 0): 4개
(15.0, 1, 2, 4, 1, '어른입맛 RED 술청년 ', 0): 2개
(14.0, 1, 2, 4, 1, '어른입맛 RED 술청년 ', 0): 2개
(13.0, 1, 3, 3, 1, '어른입맛 RED 술청년 ', 0): 1개
(14.0, 1, 3, 3, 1, '어른입맛 RED 술청년 ', 0): 2개
(13.0, 1, 3, 4, 1, '어른입맛 RED 술청년 ', 0): 53개
(12.0, 1, 3, 4, 1, '어른입맛 RED 술청년 ', 0): 5개
(14.0, 1, 3, 4, 1, '어른입맛 RED 술청년 ', 0): 10개
(15.0, 1, 3, 4, 1, '어른입맛 RED 술청년 ', 0): 1개
(13.0, 1, 3, 5, 1, '어른입맛 RED 술청년 ', 0): 21개
(12.0, 1, 3, 5, 1, '어른입맛 RED 술청년 ', 0): 2개
(14.0, 1, 3, 5, 1, '어른입맛 RED 술청년 ', 0): 51개
(15.0, 1, 3, 5, 1, '어른입맛 RED 술청년 ', 0): 7개
(14.0, 1, 4, 5, 1, '어른입맛 RED 술청년 ', 0): 1개
(14.0, 2, 2, 4, 1, '어른입맛 RED 술청년 ', 0): 1개
(13.0, 2, 3, 4, 1, '어른입맛 RED 술청년 ', 0): 2개
(14.0, 2, 3, 4, 1, '어른입맛 RED 술청년 ', 0): 1개

       도수  당도  산도  바디  타입_cate       추천솔루션 군집화  추천솔루션 군집화_n  도수_cate
294  14.0   1   3   2        2  어른입맛 WHITE 술청년            1        1
298  13.0   1   3   2        2  어른입맛 WHITE 술청년            1        1
1    13.0   1   3   3        2  어른입맛 WHITE 술청년            1        1
19   14.0   1   3   3        2  어른입맛 WHITE 술청년            1        1
135  12.0   1   3   3        2  어른입맛 WHITE 술청년            1        1
4    13.0   1   3   4        2  어른입맛 WHITE 술청년            1        1
24   12.0   1   3   4        2  어른입맛 WHITE 술청년            1        1
26   11.0   1   3   4        2  어른입맛 WHITE 술청년            1        1
51   14.0   1   3   4        2  어른입맛 WHITE 술청년            1        1
256  15.0   1   3   4        2  어른입맛 WHITE 술청년            1        1
258  13.0   1   3   5        2  어른입맛 WHITE 술청년            1        1
276  13.0   1   4   2        2  어른입맛 WHITE 술청년            1        1
307  12.0   1   4   2        2  어른입맛 WHITE 술청년            1        1
277  10.0   1   4   3        2  어른입맛 WHITE 술청년            1        1
291  13.0   1   4   3        2  어른입맛 WHITE 술청년            1        1
282  13.0   2   3   2        2  어른입맛 WHITE 술청년            1        1
284  12.0   2   3   2        2  어른입맛 WHITE 술청년            1        1
67   12.0   2   3   3        2  어른입맛 WHITE 술청년            1        1
76   10.0   2   3   3        2  어른입맛 WHITE 술청년            1        1
238  11.0   2   3   4        2  어른입맛 WHITE 술청년            1        1
321  13.0   2   3   4        2  어른입맛 WHITE 술청년            1        1
274  14.0   2   4   3        2  어른입맛 WHITE 술청년            1        1
52   10.0   1   3   3        3  어른입맛 WHITE 술청년            1        1
53   13.0   1   3   3        3  어른입맛 WHITE 술청년            1        1
198  12.0   1   3   3        3  어른입맛 WHITE 술청년            1        1
56   12.0   1   3   4        3  어른입맛 WHITE 술청년            1        1
313  12.0   1   4   2        3  어른입맛 WHITE 술청년            1        1
315  12.0   1   4   3        3  어른입맛 WHITE 술청년            1        1
92   11.0   2   3   3        3  어른입맛 WHITE 술청년            1        1
111  10.0   2   3   3        3  어른입맛 WHITE 술청년            1        1
66    9.0   2   3   4        3  어른입맛 WHITE 술청년            1        1

(14.0, 1, 3, 2, 2, '어른입맛 WHITE 술청년', 1): 2개
(13.0, 1, 3, 2, 2, '어른입맛 WHITE 술청년', 1): 1개
(13.0, 1, 3, 3, 2, '어른입맛 WHITE 술청년', 1): 27개
(14.0, 1, 3, 3, 2, '어른입맛 WHITE 술청년', 1): 8개
(12.0, 1, 3, 3, 2, '어른입맛 WHITE 술청년', 1): 7개
(13.0, 1, 3, 4, 2, '어른입맛 WHITE 술청년', 1): 5개
(12.0, 1, 3, 4, 2, '어른입맛 WHITE 술청년', 1): 2개
(11.0, 1, 3, 4, 2, '어른입맛 WHITE 술청년', 1): 1개
(14.0, 1, 3, 4, 2, '어른입맛 WHITE 술청년', 1): 4개
(15.0, 1, 3, 4, 2, '어른입맛 WHITE 술청년', 1): 1개
(13.0, 1, 3, 5, 2, '어른입맛 WHITE 술청년', 1): 1개
(13.0, 1, 4, 2, 2, '어른입맛 WHITE 술청년', 1): 1개
(12.0, 1, 4, 2, 2, '어른입맛 WHITE 술청년', 1): 1개
(10.0, 1, 4, 3, 2, '어른입맛 WHITE 술청년', 1): 1개
(13.0, 1, 4, 3, 2, '어른입맛 WHITE 술청년', 1): 1개
(13.0, 2, 3, 2, 2, '어른입맛 WHITE 술청년', 1): 2개
(12.0, 2, 3, 2, 2, '어른입맛 WHITE 술청년', 1): 1개
(12.0, 2, 3, 3, 2, '어른입맛 WHITE 술청년', 1): 3개
(10.0, 2, 3, 3, 2, '어른입맛 WHITE 술청년', 1): 1개
(11.0, 2, 3, 4, 2, '어른입맛 WHITE 술청년', 1): 1개
(13.0, 2, 3, 4, 2, '어른입맛 WHITE 술청년', 1): 1개
(14.0, 2, 4, 3, 2, '어른입맛 WHITE 술청년', 1): 1개
(10.0, 1, 3, 3, 3, '어른입맛 WHITE 술청년', 1): 1개
(13.0, 1, 3, 3, 3, '어른입맛 WHITE 술청년', 1): 1개
(12.0, 1, 3, 3, 3, '어른입맛 WHITE 술청년', 1): 2개
(12.0, 1, 3, 4, 3, '어른입맛 WHITE 술청년', 1): 8개
(12.0, 1, 4, 2, 3, '어른입맛 WHITE 술청년', 1): 1개
(12.0, 1, 4, 3, 3, '어른입맛 WHITE 술청년', 1): 1개
(11.0, 2, 3, 3, 3, '어른입맛 WHITE 술청년', 1): 2개
(10.0, 2, 3, 3, 3, '어른입맛 WHITE 술청년', 1): 2개
(9.0, 2, 3, 4, 3, '어른입맛 WHITE 술청년', 1): 1개

      도수  당도  산도  바디  타입_cate  추천솔루션 군집화  추천솔루션 군집화_n  도수_cate
86   7.0   3   3   5        1  어린이입맛 술린이            2        0
14   6.0   4   3   3        1  어린이입맛 술린이            2        0
16   6.0   5   3   3        1  어린이입맛 술린이            2        0
154  5.0   5   3   2        2  어린이입맛 술린이            2        0
128  7.0   4   3   3        3  어린이입맛 술린이            2        0
197  5.0   4   3   3        3  어린이입맛 술린이            2        0
137  7.0   5   3   4        3  어린이입맛 술린이            2        0
172  5.0   5   3   4        3  어린이입맛 술린이            2        0
306  7.0   5   3   5        3  어린이입맛 술린이            2        0

(7.0, 3, 3, 5, 1, '어린이입맛 술린이', 2): 1개
(6.0, 4, 3, 3, 1, '어린이입맛 술린이', 2): 1개
(6.0, 5, 3, 3, 1, '어린이입맛 술린이', 2): 1개
(5.0, 5, 3, 2, 2, '어린이입맛 술린이', 2): 2개
(7.0, 4, 3, 3, 3, '어린이입맛 술린이', 2): 2개
(5.0, 4, 3, 3, 3, '어린이입맛 술린이', 2): 1개
(7.0, 5, 3, 4, 3, '어린이입맛 술린이', 2): 1개
(5.0, 5, 3, 4, 3, '어린이입맛 술린이', 2): 1개
(7.0, 5, 3, 5, 3, '어린이입맛 술린이', 2): 1개

       도수  당도  산도  바디  타입_cate        추천솔루션 군집화  추천솔루션 군집화_n  도수_cate
283  13.0   3   3   2        2  어린이입맛 WHITE 술청년            3        1
120  13.0   3   3   3        2  어린이입맛 WHITE 술청년            3        1
121  12.0   4   3   2        2  어린이입맛 WHITE 술청년            3        1
68    9.0   4   3   3        2  어린이입맛 WHITE 술청년            3        1
119  12.0   4   3   3        2  어린이입맛 WHITE 술청년            3        1
78   10.0   4   3   4        2  어린이입맛 WHITE 술청년            3        1
278   8.0   4   4   3        2  어린이입맛 WHITE 술청년            3        1
79   10.0   5   2   4        2  어린이입맛 WHITE 술청년            3        1
80    8.0   5   2   5        2  어린이입맛 WHITE 술청년            3        1
15   13.0   5   3   2        2  어린이입맛 WHITE 술청년            3        1
155   9.0   5   3   2        2  어린이입맛 WHITE 술청년            3        1
75    8.0   5   3   3        2  어린이입맛 WHITE 술청년            3        1
77    8.0   5   3   4        2  어린이입맛 WHITE 술청년            3        1
122  11.0   5   3   4        2  어린이입맛 WHITE 술청년            3        1
124  12.0   5   3   4        2  어린이입맛 WHITE 술청년            3        1
202  13.0   5   3   4        2  어린이입맛 WHITE 술청년            3        1
287  10.0   5   3   4        2  어린이입맛 WHITE 술청년            3        1
279  12.0   5   4   4        2  어린이입맛 WHITE 술청년            3        1
173   9.0   5   3   4        3  어린이입맛 WHITE 술청년            3        1

(13.0, 3, 3, 2, 2, '어린이입맛 WHITE 술청년', 3): 2개
(13.0, 3, 3, 3, 2, '어린이입맛 WHITE 술청년', 3): 1개
(12.0, 4, 3, 2, 2, '어린이입맛 WHITE 술청년', 3): 2개
(9.0, 4, 3, 3, 2, '어린이입맛 WHITE 술청년', 3): 2개
(12.0, 4, 3, 3, 2, '어린이입맛 WHITE 술청년', 3): 2개
(10.0, 4, 3, 4, 2, '어린이입맛 WHITE 술청년', 3): 1개
(8.0, 4, 4, 3, 2, '어린이입맛 WHITE 술청년', 3): 1개
(10.0, 5, 2, 4, 2, '어린이입맛 WHITE 술청년', 3): 1개
(8.0, 5, 2, 5, 2, '어린이입맛 WHITE 술청년', 3): 1개
(13.0, 5, 3, 2, 2, '어린이입맛 WHITE 술청년', 3): 3개
(9.0, 5, 3, 2, 2, '어린이입맛 WHITE 술청년', 3): 1개
(8.0, 5, 3, 3, 2, '어린이입맛 WHITE 술청년', 3): 1개
(8.0, 5, 3, 4, 2, '어린이입맛 WHITE 술청년', 3): 1개
(11.0, 5, 3, 4, 2, '어린이입맛 WHITE 술청년', 3): 1개
(12.0, 5, 3, 4, 2, '어린이입맛 WHITE 술청년', 3): 2개
(13.0, 5, 3, 4, 2, '어린이입맛 WHITE 술청년', 3): 1개
(10.0, 5, 3, 4, 2, '어린이입맛 WHITE 술청년', 3): 1개
(12.0, 5, 4, 4, 2, '어린이입맛 WHITE 술청년', 3): 1개
(9.0, 5, 3, 4, 3, '어린이입맛 WHITE 술청년', 3): 1개

      도수  당도  산도  바디  타입_cate 추천솔루션 군집화  추천솔루션 군집화_n  도수_cate
89   7.0   1   3   4        1  어른입맛 술린이            4        0
96   1.0   1   3   4        1  어른입맛 술린이            4        0
87   7.0   1   3   5        1  어른입맛 술린이            4        0
88   7.0   1   3   3        2  어른입맛 술린이            4        0
163  1.0   1   3   3        2  어른입맛 술린이            4        0
32   1.0   1   3   4        2  어른입맛 술린이            4        0

(7.0, 1, 3, 4, 1, '어른입맛 술린이', 4): 2개
(1.0, 1, 3, 4, 1, '어른입맛 술린이', 4): 9개
(7.0, 1, 3, 5, 1, '어른입맛 술린이', 4): 1개
(7.0, 1, 3, 3, 2, '어른입맛 술린이', 4): 2개
(1.0, 1, 3, 3, 2, '어른입맛 술린이', 4): 1개
(1.0, 1, 3, 4, 2, '어른입맛 술린이', 4): 5개

       도수  당도  산도  바디  타입_cate      추천솔루션 군집화  추천솔루션 군집화_n  도수_cate
81   12.0   3   2   3        1  어린이입맛 RED 술청년            5        1
85   14.0   3   3   4        1  어린이입맛 RED 술청년            5        1
83   14.0   3   3   5        1  어린이입맛 RED 술청년            5        1
205  15.0   5   3   5        1  어린이입맛 RED 술청년            5        1

(12.0, 3, 2, 3, 1, '어린이입맛 RED 술청년', 5): 1개
(14.0, 3, 3, 4, 1, '어린이입맛 RED 술청년', 5): 1개
(14.0, 3, 3, 5, 1, '어린이입맛 RED 술청년', 5): 2개
(15.0, 5, 3, 5, 1, '어린이입맛 RED 술청년', 5): 1개

       도수  당도  산도  바디  타입_cate      추천솔루션 군집화  추천솔루션 군집화_n  도수_cate
236  16.0   1   3   5        1  어른입맛 RED 술른이             6        2
304  17.0   2   2   4        1  어른입맛 RED 술른이             6        2

(16.0, 1, 3, 5, 1, '어른입맛 RED 술른이 ', 6): 1개
(17.0, 2, 2, 4, 1, '어른입맛 RED 술른이 ', 6): 2개

#### 의사결정 트리 분류모델

In [188]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

x = wine_df_model[['도수_cate','당도','산도','바디','타입_cate']]
y = wine_df_model['추천솔루션 군집화_n']

dtree = DecisionTreeClassifier()

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 5)
dtree.fit(X_train, y_train)
pred = dtree.predict(X_test)

accuracy_score(y_test, pred)

1.0

In [189]:
display(x)
display(y)

     도수_cate  당도  산도  바디  타입_cate
0          1   1   2   4        1
1          1   1   3   3        2
2          1   1   3   5        1
3          1   1   3   5        1
4          1   1   3   4        2
..       ...  ..  ..  ..      ...
320        1   1   3   3        1
321        1   2   3   4        2
322        1   1   3   4        1
323        1   1   3   5        1
324        1   1   4   5        1

[325 rows x 5 columns]

0      0
1      1
2      0
3      0
4      1
      ..
320    0
321    1
322    0
323    0
324    0
Name: 추천솔루션 군집화_n, Length: 325, dtype: int32

In [190]:
# 모델 파일 저장

import pickle
import joblib

filename = 'wine_model_v3범주형.pkl'
joblib.dump(dtree, filename)

['wine_model_v3범주형.pkl']

In [191]:
# 파일 불러오기: 객체가 나올 것

mdl = joblib.load('wine_model_v3범주형.pkl')
mdl

DecisionTreeClassifier()

In [193]:
# 모델 확인

data = [1,5,4,1,1]

db_df = pd.DataFrame(columns = ['도수_cate','당도', '산도', '바디', '타입_cate'])
db_df.loc[0] = data
y_pred = mdl.predict(db_df)

y_pred[0]

5

In [195]:
# 피처별 중요도
frame = pd.DataFrame(columns = ['도수_cate','당도', '산도', '바디', '타입_cate'])
importance = pd.DataFrame(np.round(dtree.feature_importances_, 3))
pd.concat([frame, importance.transpose().rename(columns = {0: '도수_cate',
                                                           1: '당도',
                                                           2: '산도',
                                                           3: '바디',
                                                           4: '타입_cate'})], axis = 0)

  도수_cate     당도   산도   바디 타입_cate
0   0.282  0.258  0.0  0.0    0.46

In [157]:
wine_df[['추천솔루션 군집화','추천솔루션 군집화_n']].value_counts()

추천솔루션 군집화        추천솔루션 군집화_n
어른입맛 RED 술청년     0              168
어른입맛 WHITE 술청년   1               92
어린이입맛 WHITE 술청년  3               26
어른입맛 술린이         4               20
어린이입맛 술린이        2               11
어린이입맛 RED 술청년    5                5
어른입맛 RED 술른이     6                3
dtype: int64

In [200]:
#해당 조건을 원본에서 불러오기

pd.DataFrame(wine_df[(wine_df['추천솔루션 군집화_n'] == 5)][['도수','당도','산도','바디', '와인타입']].value_counts())

                     0
도수   당도 산도 바디 와인타입
14.0 3  3  5  레드 와인  2
12.0 3  2  3  레드 와인  1
14.0 3  3  4  레드 와인  1
15.0 5  3  5  레드 와인  1

### 최종 데이터프레임 생성

In [202]:
wine_df.columns

Index(['와인이름', '영어이름', '와인타입', '나라, 와이너리', '포도종', '도수', '당도', '산도', '바디', '탄닌',
       '와이너리이름', '와이너리설명', '와이너리특징', '아로마 딕셔너리', '곁들일 음식', '음식', '아로마 중분류',
       '아로마 소분류', '대표 중분류 아로마', '도수_cate', '당도_cate', '산도_cate', '바디_cate',
       '타입_cate', '도수_cate2', '당도_cate2', '산도_cate2', '바디_cate2', '타입_cate2',
       '대표 중분류 아로마1', '대표 중분류 아로마2', '추천솔루션 군집화', '상황별추천 군집화', '상황별추천 군집화_n',
       '추천솔루션 군집화_n'],
      dtype='object')

In [205]:
wine_df_final = wine_df[['와인이름', '영어이름', '와인타입', '나라, 와이너리', '포도종', '도수', '당도', '산도', '바디',
                         '와이너리이름', '와이너리설명', '와이너리특징', '아로마 딕셔너리', '곁들일 음식', '음식',
                         '상황별추천 군집화', '상황별추천 군집화_n','추천솔루션 군집화', '추천솔루션 군집화_n']]
wine_df_final

,와인이름,영어이름,와인타입,"나라, 와이너리",포도종,도수,당도,산도,바디,와이너리이름,와이너리설명,와이너리특징,아로마 딕셔너리,곁들일 음식,음식,상황별추천 군집화,상황별추천 군집화_n,추천솔루션 군집화,추천솔루션 군집화_n
0,이기갈 꼬뜨 뒤 론 레드,E.Guigal Cotes du Rhone Rouge,레드 와인,프랑스 > 론 / 이 기갈,"시라 49%, 그르나쉬 48%, 무르베드르 3%",13.0,1,2,4,이 기갈 E.Guigal,이기갈(E.Guigal)은 오늘날 프랑스 론 최고의 생산자로 꼽힌다. 1946년 에...,"""King of the Rhone"" - 영국의 와인전문지 <디캔터(Decanter)...","{'빨간 과일': ['딸기'], '허베이셔스': ['풀']}","차가운 육류요리나 가금류, 붉은육류요리, 치즈",육류 에피타이저,가족과 함께,0,어른입맛 RED 술청년,0
1,이기갈 꼬뜨 뒤 론 화이트,E.Guigal Cotes du Rhone Blanc,화이트 와인,프랑스 > 론 / 이 기갈,"비오니에 70%, 루산느 10%, 마르산느 9%, 끌레레뜨 8%, 부르불랑 3%",13.0,1,3,3,이 기갈 E.Guigal,이기갈(E.Guigal)은 오늘날 프랑스 론 최고의 생산자로 꼽힌다. 1946년 에...,"""King of the Rhone"" - 영국의 와인전문지 <디캔터(Decanter)...","{'꽃': ['아카시아'], '핵과': ['복숭아', '살구']}","해산물이나 매콤한 요리, 간단한 핑거푸드",매운음식 해산물 sweet디저트,가족과 함께,0,어른입맛 WHITE 술청년,1
2,이기갈 꼬뜨 로띠 ‘브륀 & 블롱드’,E.Guigal Cot-Rotie ‘Brune & Blonde de Guigal’,레드 와인,프랑스 > 론 / 이 기갈,"시라 96%, 비오니에 4%",13.0,1,3,5,이 기갈 E.Guigal,이기갈(E.Guigal)은 오늘날 프랑스 론 최고의 생산자로 꼽힌다. 1946년 에...,"""King of the Rhone"" - 영국의 와인전문지 <디캔터(Decanter)...","{'자연(Earthy)': ['커피', '토스트'], '오크(Oak)': ['바닐라...","붉은 육류요리, 치즈",육류 에피타이저,가족과 함께,0,어른입맛 RED 술청년,0
3,이기갈 꼬뜨 로띠 ‘샤또 당퓌’,E.Guigal Cote-Rotie ‘Chateau d’Ampuis’,레드 와인,프랑스 > 론 / 이 기갈,"시라 93%, 비오니에 7%",13.0,1,3,5,이 기갈 E.Guigal,이기갈(E.Guigal)은 오늘날 프랑스 론 최고의 생산자로 꼽힌다. 1946년 에...,"""King of the Rhone"" - 영국의 와인전문지 <디캔터(Decanter)...","{'오크(Oak)': ['바닐라'], '녹색 과일': ['배'], '빨간 과일': ...","붉은 육류요리, 치즈",육류 에피타이저,가족과 함께,0,어른입맛 RED 술청년,0
4,이기갈 꽁드리유,E.Guigal Condrieu,화이트 와인,프랑스 > 론 / 이 기갈,비오니에 100%,13.0,1,3,4,이 기갈 E.Guigal,이기갈(E.Guigal)은 오늘날 프랑스 론 최고의 생산자로 꼽힌다. 1946년 에...,"""King of the Rhone"" - 영국의 와인전문지 <디캔터(Decanter)...","{'핵과': ['복숭아', '살구']}","푸아그라, 송로버섯을 가미한 달걀요리 등 섬세한 풍미의 음식",육류,가족과 함께,0,어른입맛 WHITE 술청년,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
320,까테나 자파타 까테나 말벡,Catena Zapata Catena Malbec,레드 와인,아르헨티나 > 멘도자 / 까테나 자파타,말백 100%,14.0,1,3,3,까테나 자파타 Catena Zapata,까테나 자파타(Catena Zapata)는 아르헨티나 멘도자의 와인을 전 세계에 제...,아르헨티나 고급 와인의 선구자\r멘도자를 세계적인 와인 산지로 올려 놓은 와이너리\...,"{'자연(Earthy)': ['가죽', '미네랄'], '오크(Oak)': ['바닐라...","훈제 오리, 그릴드 치킨, 각종 육류 요리",육류,술른이 연인과함께,3,어른입맛 RED 술청년,0
321,까테나 자파타 까테나 알타 샤르도네,Catena Zapata Catena Alta Chardonnay,화이트 와인,아르헨티나 > 멘도자 / 까테나 자파타,샤르도네 100%,13.0,2,3,4,까테나 자파타 Catena Zapata,까테나 자파타(Catena Zapata)는 아르헨티나 멘도자의 와인을 전 세계에 제...,아르헨티나 고급 와인의 선구자\r멘도자를 세계적인 와인 산지로 올려 놓은 와이너리\...,"{'자연(Earthy)': ['토스트', '미네랄'], '녹색 과일': ['애플']...","신선한 해산물, 바질 오일파스타, 파마산 치즈를 곁들인 썬 드라이 토마토 샐러드",해산물 양식 에피타이저,가족과 함께,0,어른입맛 WHITE 술청년,1
322,까테나 자파타 까테나 알타 말벡,Catena Zapata Catena Alta Malbec,레드 와인,아르헨티나 > 멘도자 / 까테나 자파타,말백 100%,14.0,1,3,4,까테나 자파타 Catena Zapata,까테나 자파타(Catena Zapata)는 아르헨티나 멘도자의 와인을 전 세계에 제...,아르헨티나 고급 와인의 선구자\r멘도자를 세계적인 와인 산지로 올려 놓은 와이너리\...,"{'오크(Oak)': ['바닐라'], '빨간 과일': ['베리'], '까만 과일':...","달콤한 육포, 스테이크, 훈연 소시지, 치즈",육류 에피타이저,술른이 연인과함께,3,어른입맛 RED 술청년,0
323,까테나 자파타 니카시아 말벡,Catena Zapata Nicasia Malbec,레드 와인,아르헨티나 > 멘도자 / 까테나 자파타,말벡 100%,14.0,1,3,5,까테나 자파타 Catena Zapata,까테나 자파타(Catena Zapata)는 아르헨티나 멘도자의 와인을 전 세계에 제...,아르헨티나 고급 와인의 선구자\r멘도자를 세계적인 와인 산지로 올려 놓은 와이너리\...,"{'오크(Oak)': ['초콜릿'], '꽃': ['바이올렛'], '빨간 과일': [...","양갈비, 로스트비프, 트러플 치즈 파니니, 머쉬룸 파스타",육류 양식 에피타이저,술른이 연인과함께,3,어른입맛 RED 술청년,0
324,까테나 자파타 아르헨티노 말벡,Catena Zapata Argentino Malbec,레드 와인,아르헨티나 > 멘도자 / 까테나 자파타,말벡 100%,14.0,1,4,5,까테나 자파타 Catena Zapata,까테나 자파타(Catena Zapata)는 아르헨티나 멘도자의 와인을 전 세계에 제...,아르헨티나 고급 와인의 선구자\r멘도자를 세계적인 와인 산지로 올려 놓은 와이너리\...,"{'녹색 과일': ['배'], '빨간 과일': ['라즈베리', '베리'], '까만 ...","치즈, 육즙이 풍부한 스테이크, 양고기, 블루 치즈",육류 에피타이저,술른이 연인과함께,3,어른입맛 RED 술청년,0

#### 한줄 소개 컬럼 추가

In [212]:
x = pd.read_csv('shin_df_vivino.csv', index_col = 0)
x_merge = x[['와인이름', '한줄소개']]
x_merge

                        와인이름                                        한줄소개
0              이기갈 꼬뜨 뒤 론 레드  "King of the Rhone"으로 불리는 E.Guigal의 와인입니다.
1             이기갈 꼬뜨 뒤 론 화이트  "King of the Rhone"으로 불리는 E.Guigal의 와인입니다.
2       이기갈 꼬뜨 로띠 ‘브륀 & 블롱드’  "King of the Rhone"으로 불리는 E.Guigal의 와인입니다.
3          이기갈 꼬뜨 로띠 ‘샤또 당퓌’  "King of the Rhone"으로 불리는 E.Guigal의 와인입니다.
4                   이기갈 꽁드리유  "King of the Rhone"으로 불리는 E.Guigal의 와인입니다.
..                       ...                                         ...
892  까테나 자파타 까테나 알타 까베르네 소비뇽           최적의 시기에 수확한 포도를 선별해 만든 아르헨티나 레드와인
893        까테나 자파타 까테나 알타 말벡           최적의 시기에 수확한 포도를 선별해 만든 아르헨티나 레드와인
894          까테나 자파타 니카시아 말벡           까테나 자파타 최고도 빈야드에서 생산되는 100% 말벡 와인
895         까테나 자파타 아르헨티노 말벡                      열정의 나라, 아르헨티나의 프리미엄 와인
896       까테나 자파타 에스티바 레세르바다                        까테나 자파타 와이너리의 최상급 와인

[897 rows x 2 columns]

In [215]:
wine_real_final = pd.merge(wine_df_final, x_merge, how = 'inner')
wine_real_final = wine_real_final[['와인이름', '영어이름', '와인타입', '나라, 와이너리', '한줄소개', '포도종', '도수', '당도', '산도', '바디',
       '와이너리이름', '와이너리설명', '와이너리특징', '아로마 딕셔너리', '곁들일 음식', '음식', '상황별추천 군집화',
       '상황별추천 군집화_n', '추천솔루션 군집화', '추천솔루션 군집화_n']]

In [216]:
wine_real_final.head()

,와인이름,영어이름,와인타입,"나라, 와이너리",한줄소개,포도종,도수,당도,산도,바디,와이너리이름,와이너리설명,와이너리특징,아로마 딕셔너리,곁들일 음식,음식,상황별추천 군집화,상황별추천 군집화_n,추천솔루션 군집화,추천솔루션 군집화_n
0,이기갈 꼬뜨 뒤 론 레드,E.Guigal Cotes du Rhone Rouge,레드 와인,프랑스 > 론 / 이 기갈,"""King of the Rhone""으로 불리는 E.Guigal의 와인입니다.","시라 49%, 그르나쉬 48%, 무르베드르 3%",13.0,1,2,4,이 기갈 E.Guigal,이기갈(E.Guigal)은 오늘날 프랑스 론 최고의 생산자로 꼽힌다. 1946년 에...,"""King of the Rhone"" - 영국의 와인전문지 <디캔터(Decanter)...","{'빨간 과일': ['딸기'], '허베이셔스': ['풀']}","차가운 육류요리나 가금류, 붉은육류요리, 치즈",육류 에피타이저,가족과 함께,0,어른입맛 RED 술청년,0
1,이기갈 꼬뜨 뒤 론 화이트,E.Guigal Cotes du Rhone Blanc,화이트 와인,프랑스 > 론 / 이 기갈,"""King of the Rhone""으로 불리는 E.Guigal의 와인입니다.","비오니에 70%, 루산느 10%, 마르산느 9%, 끌레레뜨 8%, 부르불랑 3%",13.0,1,3,3,이 기갈 E.Guigal,이기갈(E.Guigal)은 오늘날 프랑스 론 최고의 생산자로 꼽힌다. 1946년 에...,"""King of the Rhone"" - 영국의 와인전문지 <디캔터(Decanter)...","{'꽃': ['아카시아'], '핵과': ['복숭아', '살구']}","해산물이나 매콤한 요리, 간단한 핑거푸드",매운음식 해산물 sweet디저트,가족과 함께,0,어른입맛 WHITE 술청년,1
2,이기갈 꼬뜨 로띠 ‘브륀 & 블롱드’,E.Guigal Cot-Rotie ‘Brune & Blonde de Guigal’,레드 와인,프랑스 > 론 / 이 기갈,"""King of the Rhone""으로 불리는 E.Guigal의 와인입니다.","시라 96%, 비오니에 4%",13.0,1,3,5,이 기갈 E.Guigal,이기갈(E.Guigal)은 오늘날 프랑스 론 최고의 생산자로 꼽힌다. 1946년 에...,"""King of the Rhone"" - 영국의 와인전문지 <디캔터(Decanter)...","{'자연(Earthy)': ['커피', '토스트'], '오크(Oak)': ['바닐라...","붉은 육류요리, 치즈",육류 에피타이저,가족과 함께,0,어른입맛 RED 술청년,0
3,이기갈 꼬뜨 로띠 ‘샤또 당퓌’,E.Guigal Cote-Rotie ‘Chateau d’Ampuis’,레드 와인,프랑스 > 론 / 이 기갈,"""King of the Rhone""으로 불리는 E.Guigal의 와인입니다.","시라 93%, 비오니에 7%",13.0,1,3,5,이 기갈 E.Guigal,이기갈(E.Guigal)은 오늘날 프랑스 론 최고의 생산자로 꼽힌다. 1946년 에...,"""King of the Rhone"" - 영국의 와인전문지 <디캔터(Decanter)...","{'오크(Oak)': ['바닐라'], '녹색 과일': ['배'], '빨간 과일': ...","붉은 육류요리, 치즈",육류 에피타이저,가족과 함께,0,어른입맛 RED 술청년,0
4,이기갈 꽁드리유,E.Guigal Condrieu,화이트 와인,프랑스 > 론 / 이 기갈,"""King of the Rhone""으로 불리는 E.Guigal의 와인입니다.",비오니에 100%,13.0,1,3,4,이 기갈 E.Guigal,이기갈(E.Guigal)은 오늘날 프랑스 론 최고의 생산자로 꼽힌다. 1946년 에...,"""King of the Rhone"" - 영국의 와인전문지 <디캔터(Decanter)...","{'핵과': ['복숭아', '살구']}","푸아그라, 송로버섯을 가미한 달걀요리 등 섬세한 풍미의 음식",육류,가족과 함께,0,어른입맛 WHITE 술청년,1

In [239]:
wine_real_final

,와인이름,영어이름,와인타입,"나라, 와이너리",한줄소개,포도종,도수,당도,산도,바디,와이너리이름,와이너리설명,와이너리특징,아로마 딕셔너리,곁들일 음식,음식,상황별추천 군집화,상황별추천 군집화_n,추천솔루션 군집화,추천솔루션 군집화_n
0,이기갈 꼬뜨 뒤 론 레드,E.Guigal Cotes du Rhone Rouge,레드 와인,프랑스 > 론 / 이 기갈,"""King of the Rhone""으로 불리는 E.Guigal의 와인입니다.","시라 49%, 그르나쉬 48%, 무르베드르 3%",13.0,1,2,4,이 기갈 E.Guigal,이기갈(E.Guigal)은 오늘날 프랑스 론 최고의 생산자로 꼽힌다. 1946년 에...,"""King of the Rhone"" - 영국의 와인전문지 <디캔터(Decanter)...","{'빨간 과일': ['딸기'], '허베이셔스': ['풀']}","차가운 육류요리나 가금류, 붉은육류요리, 치즈",육류 에피타이저,가족과 함께,0,어른입맛 RED 술청년,0
1,이기갈 꼬뜨 뒤 론 화이트,E.Guigal Cotes du Rhone Blanc,화이트 와인,프랑스 > 론 / 이 기갈,"""King of the Rhone""으로 불리는 E.Guigal의 와인입니다.","비오니에 70%, 루산느 10%, 마르산느 9%, 끌레레뜨 8%, 부르불랑 3%",13.0,1,3,3,이 기갈 E.Guigal,이기갈(E.Guigal)은 오늘날 프랑스 론 최고의 생산자로 꼽힌다. 1946년 에...,"""King of the Rhone"" - 영국의 와인전문지 <디캔터(Decanter)...","{'꽃': ['아카시아'], '핵과': ['복숭아', '살구']}","해산물이나 매콤한 요리, 간단한 핑거푸드",매운음식 해산물 sweet디저트,가족과 함께,0,어른입맛 WHITE 술청년,1
2,이기갈 꼬뜨 로띠 ‘브륀 & 블롱드’,E.Guigal Cot-Rotie ‘Brune & Blonde de Guigal’,레드 와인,프랑스 > 론 / 이 기갈,"""King of the Rhone""으로 불리는 E.Guigal의 와인입니다.","시라 96%, 비오니에 4%",13.0,1,3,5,이 기갈 E.Guigal,이기갈(E.Guigal)은 오늘날 프랑스 론 최고의 생산자로 꼽힌다. 1946년 에...,"""King of the Rhone"" - 영국의 와인전문지 <디캔터(Decanter)...","{'자연(Earthy)': ['커피', '토스트'], '오크(Oak)': ['바닐라...","붉은 육류요리, 치즈",육류 에피타이저,가족과 함께,0,어른입맛 RED 술청년,0
3,이기갈 꼬뜨 로띠 ‘샤또 당퓌’,E.Guigal Cote-Rotie ‘Chateau d’Ampuis’,레드 와인,프랑스 > 론 / 이 기갈,"""King of the Rhone""으로 불리는 E.Guigal의 와인입니다.","시라 93%, 비오니에 7%",13.0,1,3,5,이 기갈 E.Guigal,이기갈(E.Guigal)은 오늘날 프랑스 론 최고의 생산자로 꼽힌다. 1946년 에...,"""King of the Rhone"" - 영국의 와인전문지 <디캔터(Decanter)...","{'오크(Oak)': ['바닐라'], '녹색 과일': ['배'], '빨간 과일': ...","붉은 육류요리, 치즈",육류 에피타이저,가족과 함께,0,어른입맛 RED 술청년,0
4,이기갈 꽁드리유,E.Guigal Condrieu,화이트 와인,프랑스 > 론 / 이 기갈,"""King of the Rhone""으로 불리는 E.Guigal의 와인입니다.",비오니에 100%,13.0,1,3,4,이 기갈 E.Guigal,이기갈(E.Guigal)은 오늘날 프랑스 론 최고의 생산자로 꼽힌다. 1946년 에...,"""King of the Rhone"" - 영국의 와인전문지 <디캔터(Decanter)...","{'핵과': ['복숭아', '살구']}","푸아그라, 송로버섯을 가미한 달걀요리 등 섬세한 풍미의 음식",육류,가족과 함께,0,어른입맛 WHITE 술청년,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
320,까테나 자파타 까테나 말벡,Catena Zapata Catena Malbec,레드 와인,아르헨티나 > 멘도자 / 까테나 자파타,부드러운 탄닌감과 선명한 산도의 말벡 100% 와인,말백 100%,14.0,1,3,3,까테나 자파타 Catena Zapata,까테나 자파타(Catena Zapata)는 아르헨티나 멘도자의 와인을 전 세계에 제...,아르헨티나 고급 와인의 선구자\r멘도자를 세계적인 와인 산지로 올려 놓은 와이너리\...,"{'자연(Earthy)': ['가죽', '미네랄'], '오크(Oak)': ['바닐라...","훈제 오리, 그릴드 치킨, 각종 육류 요리",육류,술른이 연인과함께,3,어른입맛 RED 술청년,0
321,까테나 자파타 까테나 알타 샤르도네,Catena Zapata Catena Alta Chardonnay,화이트 와인,아르헨티나 > 멘도자 / 까테나 자파타,최적의 시기에 수확한 포도를 선별해 만든 아르헨티나 화이트와인,샤르도네 100%,13.0,2,3,4,까테나 자파타 Catena Zapata,까테나 자파타(Catena Zapata)는 아르헨티나 멘도자의 와인을 전 세계에 제...,아르헨티나 고급 와인의 선구자\r멘도자를 세계적인 와인 산지로 올려 놓은 와이너리\...,"{'자연(Earthy)': ['토스트', '미네랄'], '녹색 과일': ['애플']...","신선한 해산물, 바질 오일파스타, 파마산 치즈를 곁들인 썬 드라이 토마토 샐러드",해산물 양식 에피타이저,가족과 함께,0,어른입맛 WHITE 술청년,1
322,까테나 자파타 까테나 알타 말벡,Catena Zapata Catena Alta Malbec,레드 와인,아르헨티나 > 멘도자 / 까테나 자파타,최적의 시기에 수확한 포도를 선별해 만든 아르헨티나 레드와인,말백 100%,14.0,1,3,4,까테나 자파타 Catena Zapata,까테나 자파타(Catena Zapata)는 아르헨티나 멘도자의 와인을 전 세계에 제...,아르헨티나 고급 와인의 선구자\r멘도자를 세계적인 와인 산지로 올려 놓은 와이너리\...,"{'오크(Oak)': ['바닐라'], '빨간 과일': ['베리'], '까만 과일':...","달콤한 육포, 스테이크, 훈연 소시지, 치즈",육류 에피타이저,술른이 연인과함께,3,어른입맛 RED 술청년,0
323,까테나 자파타 니카시아 말벡,Catena Zapata Nicasia Malbec,레드 와인,아르헨티나 > 멘도자 / 까테나 자파타,까테나 자파타 최고도 빈야드에서 생산되는 100% 말벡 와인,말벡 100%,14.0,1,3,5,까테나 자파타 Catena Zapata,까테나 자파타(Catena Zapata)는 아르헨티나 멘도자의 와인을 전 세계에 제...,아르헨티나 고급 와인의 선구자\r멘도자를 세계적인 와인 산지로 올려 놓은 와이너리\...,"{'오크(Oak)': ['초콜릿'], '꽃': ['바이올렛'], '빨간 과일': [...","양갈비, 로스트비프, 트러플 치즈 파니니, 머쉬룸 파스타",육류 양식 에피타이저,술른이 연인과함께,3,어른입맛 RED 술청년,0
324,까테나 자파타 아르헨티노 말벡,Catena Zapata Argentino Malbec,레드 와인,아르헨티나 > 멘도자 / 까테나 자파타,"열정의 나라, 아르헨티나의 프리미엄 와인",말벡 100%,14.0,1,4,5,까테나 자파타 Catena Zapata,까테나 자파타(Catena Zapata)는 아르헨티나 멘도자의 와인을 전 세계에 제...,아르헨티나 고급 와인의 선구자\r멘도자를 세계적인 와인 산지로 올려 놓은 와이너리\...,"{'녹색 과일': ['배'], '빨간 과일': ['라즈베리', '베리'], '까만 ...","치즈, 육즙이 풍부한 스테이크, 양고기, 블루 치즈",육류 에피타이저,술른이 연인과함께,3,어른입맛 RED 술청년,0

## 상황별 추천시스템을 위한 군집화

#### 상황별 추천 컬럼 확인

In [230]:
# 확인
pd.options.display.max_rows = 100

for i in range(5):
    x = wine_df_final[wine_df_final['상황별추천 군집화_n']==i][['도수','당도','산도','음식', '상황별추천 군집화_n', '상황별추천 군집화']]
    x_dup = x.drop_duplicates()
    display(x_dup)

       도수  당도  산도                     음식  상황별추천 군집화_n 상황별추천 군집화
0    13.0   1   2               육류 에피타이저            0    가족과 함께
1    13.0   1   3      매운음식 해산물 sweet디저트            0    가족과 함께
2    13.0   1   3               육류 에피타이저            0    가족과 함께
4    13.0   1   3                     육류            0    가족과 함께
6    12.0   1   3               육류 에피타이저            0    가족과 함께
7    13.0   1   3         매운음식 해산물 에피타이저            0    가족과 함께
8    13.0   1   3                 육류 해산물            0    가족과 함께
15   13.0   5   3         sweet디저트 에피타이저            0    가족과 함께
24   12.0   1   3               해산물 매운음식            0    가족과 함께
25   12.0   1   3                  육류 양식            0    가족과 함께
27   13.0   1   3                  육류 양식            0    가족과 함께
34   13.0   1   3              해산물 에피타이저            0    가족과 함께
39   13.0   1   3            육류 양식 에피타이저            0    가족과 함께
56   12.0   1   3                 육류 해산물            0    가족과 함께
57   12.0   1   3           육류 해산물 에피타이저            0    가족과 함께
61   13.0   1   3  sweet디저트 해산물 양식 에피타이저            0    가족과 함께
64   13.0   2   3            육류 양식 에피타이저            0    가족과 함께
67   12.0   2   3              해산물 에피타이저            0    가족과 함께
81   12.0   3   2         sweet디저트 에피타이저            0    가족과 함께
117  12.0   2   3                    해산물            0    가족과 함께
119  12.0   4   3                 육류 해산물            0    가족과 함께
120  13.0   3   3           육류 해산물 에피타이저            0    가족과 함께
121  12.0   4   3                    해산물            0    가족과 함께
123  13.0   1   3           육류 해산물 에피타이저            0    가족과 함께
124  12.0   5   3         sweet디저트 에피타이저            0    가족과 함께
141  13.0   1   3                    해산물            0    가족과 함께
156  12.0   1   3              육류 해산물 양식            0    가족과 함께
185  13.0   1   3        육류 해산물 양식 에피타이저            0    가족과 함께
188  13.0   1   3              육류 해산물 양식            0    가족과 함께
189  12.0   1   3            육류 양식 에피타이저            0    가족과 함께
198  12.0   1   3               sweet디저트            0    가족과 함께
209  13.0   1   3        육류 해산물 sweet디저트            0    가족과 함께
211  13.0   1   3             육류 양식 매운음식            0    가족과 함께
213  13.0   1   3                육류 중국음식            0    가족과 함께
221  13.0   1   3         육류 해산물 양식 매운음식            0    가족과 함께
243  12.0   1   3              해산물 에피타이저            0    가족과 함께
258  13.0   1   3            육류 해산물 매운음식            0    가족과 함께
260  12.0   1   3                     육류            0    가족과 함께
263  13.0   1   3         육류 해산물 양식 중국음식            0    가족과 함께
264  12.0   1   3               양식 에피타이저            0    가족과 함께
267  12.0   1   3    매운음식 해산물 중국음식 에피타이저            0    가족과 함께
276  13.0   1   4           육류 해산물 에피타이저            0    가족과 함께
279  12.0   5   4         sweet디저트 에피타이저            0    가족과 함께
282  13.0   2   3                  에피타이저            0    가족과 함께
283  13.0   3   3                     육류            0    가족과 함께
284  12.0   2   3                 육류 해산물            0    가족과 함께
285  13.0   2   3                    해산물            0    가족과 함께
286  13.0   3   3               육류 에피타이저            0    가족과 함께
288  12.0   5   3                  에피타이저            0    가족과 함께
290  13.0   1   2              해산물 에피타이저            0    가족과 함께
291  13.0   1   4            육류 해산물 중국음식            0    가족과 함께
293  13.0   1   2           육류 해산물 에피타이저            0    가족과 함께
296  13.0   1   2                     육류            0    가족과 함께
298  13.0   1   3               해산물 중국음식            0    가족과 함께
302  13.0   2   3                  육류 양식            0    가족과 함께
307  12.0   1   4                    해산물            0    가족과 함께
311  12.0   1   3     sweet디저트 해산물 에피타이저            0    가족과 함께
313  12.0   1   4      sweet디저트 양식 에피타이저            0    가족과 함께
315  12.0   1   4              해산물 에피타이저            0    가족과 함께
319  13.0   1   3     sweet디저트 해산물 에피타이저            0    가족과 함께
321  13.0   2   3           해산물 양식 에피타이저            0    가족과 함께

      도수  당도  산도            음식  상황별추천 군집화_n   상황별추천 군집화
32   1.0   1   3  해산물 양식 에피타이저            1  달콤한 친구와 함께
96   1.0   1   3      육류 에피타이저            1  달콤한 친구와 함께
100  1.0   1   3         육류 양식            1  달콤한 친구와 함께
114  1.0   1   3        육류 해산물            1  달콤한 친구와 함께
152  1.0   1   3  육류 해산물 에피타이저            1  달콤한 친구와 함께

      도수  당도  산도                      음식  상황별추천 군집화_n  상황별추천 군집화
14   6.0   4   3       육류 sweet디저트 에피타이저            2  술린이 연인과함께
16   6.0   5   3       육류 sweet디저트 에피타이저            2  술린이 연인과함께
75   8.0   5   3             육류 해산물 매운음식            2  술린이 연인과함께
77   8.0   5   3                sweet디저트            2  술린이 연인과함께
80   8.0   5   2                sweet디저트            2  술린이 연인과함께
86   7.0   3   3                   육류 양식            2  술린이 연인과함께
87   7.0   1   3                   육류 양식            2  술린이 연인과함께
88   7.0   1   3         육류 해산물 양식 에피타이저            2  술린이 연인과함께
128  7.0   4   3            육류 해산물 에피타이저            2  술린이 연인과함께
137  7.0   5   3                     디저트            2  술린이 연인과함께
154  5.0   5   3  육류 매운음식 sweet디저트 에피타이저            2  술린이 연인과함께
165  7.0   4   3          sweet디저트 에피타이저            2  술린이 연인과함께
172  5.0   5   3                sweet디저트            2  술린이 연인과함께
197  5.0   4   3                  육류 해산물            2  술린이 연인과함께
278  8.0   4   4                  육류 해산물            2  술린이 연인과함께
306  7.0   5   3                   에피타이저            2  술린이 연인과함께

       도수  당도  산도                     음식  상황별추천 군집화_n  상황별추천 군집화
10   14.0   1   3               육류 에피타이저            3  술른이 연인과함께
18   14.0   1   3            육류 양식 에피타이저            3  술른이 연인과함께
19   14.0   1   3           육류 해산물 에피타이저            3  술른이 연인과함께
20   14.0   1   3                     육류            3  술른이 연인과함께
23   14.0   1   3           해산물 양식 에피타이저            3  술른이 연인과함께
31   14.0   1   3                  육류 양식            3  술른이 연인과함께
51   14.0   1   3                    해산물            3  술른이 연인과함께
54   14.0   1   3              해산물 에피타이저            3  술른이 연인과함께
69   15.0   1   3            육류 양식 에피타이저            3  술른이 연인과함께
73   14.0   1   3      육류 매운음식 해산물 에피타이저            3  술른이 연인과함께
82   14.0   1   3       육류 매운음식 양식 에피타이저            3  술른이 연인과함께
83   14.0   3   3               육류 에피타이저            3  술른이 연인과함께
84   14.0   3   3                  육류 양식            3  술른이 연인과함께
85   14.0   3   3            육류 양식 에피타이저            3  술른이 연인과함께
107  15.0   1   3               육류 에피타이저            3  술른이 연인과함께
110  14.0   1   3       육류 매운음식 sweet디저트            3  술른이 연인과함께
129  15.0   1   3       육류 매운음식 양식 에피타이저            3  술른이 연인과함께
170  14.0   1   3              육류 해산물 양식            3  술른이 연인과함께
171  14.0   1   3     육류 해산물 양식 sweet디저트            3  술른이 연인과함께
175  15.0   1   3                  육류 양식            3  술른이 연인과함께
205  15.0   5   3         sweet디저트 에피타이저            3  술른이 연인과함께
215  14.0   1   3   육류 sweet디저트 양식 에피타이저            3  술른이 연인과함께
216  14.0   1   3  육류 sweet디저트 해산물 에피타이저            3  술른이 연인과함께
224  14.0   1   3        육류 해산물 sweet디저트            3  술른이 연인과함께
225  14.0   1   3                육류 중국음식            3  술른이 연인과함께
231  15.0   1   3                     육류            3  술른이 연인과함께
236  16.0   1   3                     육류            3  술른이 연인과함께
254  14.0   1   1                     육류            3  술른이 연인과함께
256  15.0   1   3           육류 해산물 에피타이저            3  술른이 연인과함께
266  14.0   1   3                 육류 해산물            3  술른이 연인과함께
271  14.0   1   3     sweet디저트 해산물 에피타이저            3  술른이 연인과함께
274  14.0   2   4           육류 해산물 에피타이저            3  술른이 연인과함께
292  15.0   1   2           육류 해산물 에피타이저            3  술른이 연인과함께
294  14.0   1   3               해산물 중국음식            3  술른이 연인과함께
295  14.0   1   2                     육류            3  술른이 연인과함께
297  15.0   1   2                     육류            3  술른이 연인과함께
301  14.0   2   3                  육류 양식            3  술른이 연인과함께
303  14.0   2   2                  육류 양식            3  술른이 연인과함께
304  17.0   2   2               육류 에피타이저            3  술른이 연인과함께
317  14.0   1   3                 해산물 양식            3  술른이 연인과함께
324  14.0   1   4               육류 에피타이저            3  술른이 연인과함께

       도수  당도  산도                          음식  상황별추천 군집화_n   상황별추천 군집화
26   11.0   1   3             육류 해산물 양식 에피타이저            4  화끈한 친구와 함께
52   10.0   1   3                          양식            4  화끈한 친구와 함께
66    9.0   2   3     매운음식 sweet디저트 해산물 에피타이저            4  화끈한 친구와 함께
68    9.0   4   3                    sweet디저트            4  화끈한 친구와 함께
74    9.0   4   3                 육류 해산물 매운음식            4  화끈한 친구와 함께
76   10.0   2   3                 육류 해산물 매운음식            4  화끈한 친구와 함께
78   10.0   4   3  에피타이저 해산물 매운음식 육류 sweet디저트            4  화끈한 친구와 함께
79   10.0   5   2                    sweet디저트            4  화끈한 친구와 함께
92   11.0   2   3          sweet디저트 해산물 에피타이저            4  화끈한 친구와 함께
111  10.0   2   3                 육류 해산물 중국음식            4  화끈한 친구와 함께
112  10.0   2   3              육류 해산물 양식 매운음식            4  화끈한 친구와 함께
122  11.0   5   3                    sweet디저트            4  화끈한 친구와 함께
155   9.0   5   3      육류 매운음식 sweet디저트 에피타이저            4  화끈한 친구와 함께
164  11.0   2   3                        매운음식            4  화끈한 친구와 함께
173   9.0   5   3           육류 sweet디저트 에피타이저            4  화끈한 친구와 함께
238  11.0   2   3                          육류            4  화끈한 친구와 함께
277  10.0   1   4                          육류            4  화끈한 친구와 함께
287  10.0   5   3              sweet디저트 에피타이저            4  화끈한 친구와 함께

In [233]:
wine_real_final['상황별추천 군집화'] = wine_real_final['상황별추천 군집화'].replace(['달콤한 친구와 함께','술린이 연인과함께'],
                                                                ['술린이 연인과함께','달콤한 친구와 함께'])
wine_real_final

,와인이름,영어이름,와인타입,"나라, 와이너리",한줄소개,포도종,도수,당도,산도,바디,와이너리이름,와이너리설명,와이너리특징,아로마 딕셔너리,곁들일 음식,음식,상황별추천 군집화,상황별추천 군집화_n,추천솔루션 군집화,추천솔루션 군집화_n
0,이기갈 꼬뜨 뒤 론 레드,E.Guigal Cotes du Rhone Rouge,레드 와인,프랑스 > 론 / 이 기갈,"""King of the Rhone""으로 불리는 E.Guigal의 와인입니다.","시라 49%, 그르나쉬 48%, 무르베드르 3%",13.0,1,2,4,이 기갈 E.Guigal,이기갈(E.Guigal)은 오늘날 프랑스 론 최고의 생산자로 꼽힌다. 1946년 에...,"""King of the Rhone"" - 영국의 와인전문지 <디캔터(Decanter)...","{'빨간 과일': ['딸기'], '허베이셔스': ['풀']}","차가운 육류요리나 가금류, 붉은육류요리, 치즈",육류 에피타이저,가족과 함께,0,어른입맛 RED 술청년,0
1,이기갈 꼬뜨 뒤 론 화이트,E.Guigal Cotes du Rhone Blanc,화이트 와인,프랑스 > 론 / 이 기갈,"""King of the Rhone""으로 불리는 E.Guigal의 와인입니다.","비오니에 70%, 루산느 10%, 마르산느 9%, 끌레레뜨 8%, 부르불랑 3%",13.0,1,3,3,이 기갈 E.Guigal,이기갈(E.Guigal)은 오늘날 프랑스 론 최고의 생산자로 꼽힌다. 1946년 에...,"""King of the Rhone"" - 영국의 와인전문지 <디캔터(Decanter)...","{'꽃': ['아카시아'], '핵과': ['복숭아', '살구']}","해산물이나 매콤한 요리, 간단한 핑거푸드",매운음식 해산물 sweet디저트,가족과 함께,0,어른입맛 WHITE 술청년,1
2,이기갈 꼬뜨 로띠 ‘브륀 & 블롱드’,E.Guigal Cot-Rotie ‘Brune & Blonde de Guigal’,레드 와인,프랑스 > 론 / 이 기갈,"""King of the Rhone""으로 불리는 E.Guigal의 와인입니다.","시라 96%, 비오니에 4%",13.0,1,3,5,이 기갈 E.Guigal,이기갈(E.Guigal)은 오늘날 프랑스 론 최고의 생산자로 꼽힌다. 1946년 에...,"""King of the Rhone"" - 영국의 와인전문지 <디캔터(Decanter)...","{'자연(Earthy)': ['커피', '토스트'], '오크(Oak)': ['바닐라...","붉은 육류요리, 치즈",육류 에피타이저,가족과 함께,0,어른입맛 RED 술청년,0
3,이기갈 꼬뜨 로띠 ‘샤또 당퓌’,E.Guigal Cote-Rotie ‘Chateau d’Ampuis’,레드 와인,프랑스 > 론 / 이 기갈,"""King of the Rhone""으로 불리는 E.Guigal의 와인입니다.","시라 93%, 비오니에 7%",13.0,1,3,5,이 기갈 E.Guigal,이기갈(E.Guigal)은 오늘날 프랑스 론 최고의 생산자로 꼽힌다. 1946년 에...,"""King of the Rhone"" - 영국의 와인전문지 <디캔터(Decanter)...","{'오크(Oak)': ['바닐라'], '녹색 과일': ['배'], '빨간 과일': ...","붉은 육류요리, 치즈",육류 에피타이저,가족과 함께,0,어른입맛 RED 술청년,0
4,이기갈 꽁드리유,E.Guigal Condrieu,화이트 와인,프랑스 > 론 / 이 기갈,"""King of the Rhone""으로 불리는 E.Guigal의 와인입니다.",비오니에 100%,13.0,1,3,4,이 기갈 E.Guigal,이기갈(E.Guigal)은 오늘날 프랑스 론 최고의 생산자로 꼽힌다. 1946년 에...,"""King of the Rhone"" - 영국의 와인전문지 <디캔터(Decanter)...","{'핵과': ['복숭아', '살구']}","푸아그라, 송로버섯을 가미한 달걀요리 등 섬세한 풍미의 음식",육류,가족과 함께,0,어른입맛 WHITE 술청년,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
320,까테나 자파타 까테나 말벡,Catena Zapata Catena Malbec,레드 와인,아르헨티나 > 멘도자 / 까테나 자파타,부드러운 탄닌감과 선명한 산도의 말벡 100% 와인,말백 100%,14.0,1,3,3,까테나 자파타 Catena Zapata,까테나 자파타(Catena Zapata)는 아르헨티나 멘도자의 와인을 전 세계에 제...,아르헨티나 고급 와인의 선구자\r멘도자를 세계적인 와인 산지로 올려 놓은 와이너리\...,"{'자연(Earthy)': ['가죽', '미네랄'], '오크(Oak)': ['바닐라...","훈제 오리, 그릴드 치킨, 각종 육류 요리",육류,술른이 연인과함께,3,어른입맛 RED 술청년,0
321,까테나 자파타 까테나 알타 샤르도네,Catena Zapata Catena Alta Chardonnay,화이트 와인,아르헨티나 > 멘도자 / 까테나 자파타,최적의 시기에 수확한 포도를 선별해 만든 아르헨티나 화이트와인,샤르도네 100%,13.0,2,3,4,까테나 자파타 Catena Zapata,까테나 자파타(Catena Zapata)는 아르헨티나 멘도자의 와인을 전 세계에 제...,아르헨티나 고급 와인의 선구자\r멘도자를 세계적인 와인 산지로 올려 놓은 와이너리\...,"{'자연(Earthy)': ['토스트', '미네랄'], '녹색 과일': ['애플']...","신선한 해산물, 바질 오일파스타, 파마산 치즈를 곁들인 썬 드라이 토마토 샐러드",해산물 양식 에피타이저,가족과 함께,0,어른입맛 WHITE 술청년,1
322,까테나 자파타 까테나 알타 말벡,Catena Zapata Catena Alta Malbec,레드 와인,아르헨티나 > 멘도자 / 까테나 자파타,최적의 시기에 수확한 포도를 선별해 만든 아르헨티나 레드와인,말백 100%,14.0,1,3,4,까테나 자파타 Catena Zapata,까테나 자파타(Catena Zapata)는 아르헨티나 멘도자의 와인을 전 세계에 제...,아르헨티나 고급 와인의 선구자\r멘도자를 세계적인 와인 산지로 올려 놓은 와이너리\...,"{'오크(Oak)': ['바닐라'], '빨간 과일': ['베리'], '까만 과일':...","달콤한 육포, 스테이크, 훈연 소시지, 치즈",육류 에피타이저,술른이 연인과함께,3,어른입맛 RED 술청년,0
323,까테나 자파타 니카시아 말벡,Catena Zapata Nicasia Malbec,레드 와인,아르헨티나 > 멘도자 / 까테나 자파타,까테나 자파타 최고도 빈야드에서 생산되는 100% 말벡 와인,말벡 100%,14.0,1,3,5,까테나 자파타 Catena Zapata,까테나 자파타(Catena Zapata)는 아르헨티나 멘도자의 와인을 전 세계에 제...,아르헨티나 고급 와인의 선구자\r멘도자를 세계적인 와인 산지로 올려 놓은 와이너리\...,"{'오크(Oak)': ['초콜릿'], '꽃': ['바이올렛'], '빨간 과일': [...","양갈비, 로스트비프, 트러플 치즈 파니니, 머쉬룸 파스타",육류 양식 에피타이저,술른이 연인과함께,3,어른입맛 RED 술청년,0
324,까테나 자파타 아르헨티노 말벡,Catena Zapata Argentino Malbec,레드 와인,아르헨티나 > 멘도자 / 까테나 자파타,"열정의 나라, 아르헨티나의 프리미엄 와인",말벡 100%,14.0,1,4,5,까테나 자파타 Catena Zapata,까테나 자파타(Catena Zapata)는 아르헨티나 멘도자의 와인을 전 세계에 제...,아르헨티나 고급 와인의 선구자\r멘도자를 세계적인 와인 산지로 올려 놓은 와이너리\...,"{'녹색 과일': ['배'], '빨간 과일': ['라즈베리', '베리'], '까만 ...","치즈, 육즙이 풍부한 스테이크, 양고기, 블루 치즈",육류 에피타이저,술른이 연인과함께,3,어른입맛 RED 술청년,0

In [234]:
# 확인
pd.options.display.max_rows = 100
for i in range(5):
    x = wine_real_final[wine_real_final['상황별추천 군집화_n']==i][['도수','당도','산도','음식', '상황별추천 군집화_n', '상황별추천 군집화']]
    x_dup = x.drop_duplicates()
    display(x_dup)

       도수  당도  산도                     음식  상황별추천 군집화_n 상황별추천 군집화
0    13.0   1   2               육류 에피타이저            0    가족과 함께
1    13.0   1   3      매운음식 해산물 sweet디저트            0    가족과 함께
2    13.0   1   3               육류 에피타이저            0    가족과 함께
4    13.0   1   3                     육류            0    가족과 함께
6    12.0   1   3               육류 에피타이저            0    가족과 함께
7    13.0   1   3         매운음식 해산물 에피타이저            0    가족과 함께
8    13.0   1   3                 육류 해산물            0    가족과 함께
15   13.0   5   3         sweet디저트 에피타이저            0    가족과 함께
24   12.0   1   3               해산물 매운음식            0    가족과 함께
25   12.0   1   3                  육류 양식            0    가족과 함께
27   13.0   1   3                  육류 양식            0    가족과 함께
34   13.0   1   3              해산물 에피타이저            0    가족과 함께
39   13.0   1   3            육류 양식 에피타이저            0    가족과 함께
56   12.0   1   3                 육류 해산물            0    가족과 함께
57   12.0   1   3           육류 해산물 에피타이저            0    가족과 함께
61   13.0   1   3  sweet디저트 해산물 양식 에피타이저            0    가족과 함께
64   13.0   2   3            육류 양식 에피타이저            0    가족과 함께
67   12.0   2   3              해산물 에피타이저            0    가족과 함께
81   12.0   3   2         sweet디저트 에피타이저            0    가족과 함께
117  12.0   2   3                    해산물            0    가족과 함께
119  12.0   4   3                 육류 해산물            0    가족과 함께
120  13.0   3   3           육류 해산물 에피타이저            0    가족과 함께
121  12.0   4   3                    해산물            0    가족과 함께
123  13.0   1   3           육류 해산물 에피타이저            0    가족과 함께
124  12.0   5   3         sweet디저트 에피타이저            0    가족과 함께
141  13.0   1   3                    해산물            0    가족과 함께
156  12.0   1   3              육류 해산물 양식            0    가족과 함께
185  13.0   1   3        육류 해산물 양식 에피타이저            0    가족과 함께
188  13.0   1   3              육류 해산물 양식            0    가족과 함께
189  12.0   1   3            육류 양식 에피타이저            0    가족과 함께
198  12.0   1   3               sweet디저트            0    가족과 함께
209  13.0   1   3        육류 해산물 sweet디저트            0    가족과 함께
211  13.0   1   3             육류 양식 매운음식            0    가족과 함께
213  13.0   1   3                육류 중국음식            0    가족과 함께
221  13.0   1   3         육류 해산물 양식 매운음식            0    가족과 함께
243  12.0   1   3              해산물 에피타이저            0    가족과 함께
258  13.0   1   3            육류 해산물 매운음식            0    가족과 함께
260  12.0   1   3                     육류            0    가족과 함께
263  13.0   1   3         육류 해산물 양식 중국음식            0    가족과 함께
264  12.0   1   3               양식 에피타이저            0    가족과 함께
267  12.0   1   3    매운음식 해산물 중국음식 에피타이저            0    가족과 함께
276  13.0   1   4           육류 해산물 에피타이저            0    가족과 함께
279  12.0   5   4         sweet디저트 에피타이저            0    가족과 함께
282  13.0   2   3                  에피타이저            0    가족과 함께
283  13.0   3   3                     육류            0    가족과 함께
284  12.0   2   3                 육류 해산물            0    가족과 함께
285  13.0   2   3                    해산물            0    가족과 함께
286  13.0   3   3               육류 에피타이저            0    가족과 함께
288  12.0   5   3                  에피타이저            0    가족과 함께
290  13.0   1   2              해산물 에피타이저            0    가족과 함께
291  13.0   1   4            육류 해산물 중국음식            0    가족과 함께
293  13.0   1   2           육류 해산물 에피타이저            0    가족과 함께
296  13.0   1   2                     육류            0    가족과 함께
298  13.0   1   3               해산물 중국음식            0    가족과 함께
302  13.0   2   3                  육류 양식            0    가족과 함께
307  12.0   1   4                    해산물            0    가족과 함께
311  12.0   1   3     sweet디저트 해산물 에피타이저            0    가족과 함께
313  12.0   1   4      sweet디저트 양식 에피타이저            0    가족과 함께
315  12.0   1   4              해산물 에피타이저            0    가족과 함께
319  13.0   1   3     sweet디저트 해산물 에피타이저            0    가족과 함께
321  13.0   2   3           해산물 양식 에피타이저            0    가족과 함께

      도수  당도  산도            음식  상황별추천 군집화_n  상황별추천 군집화
32   1.0   1   3  해산물 양식 에피타이저            1  술린이 연인과함께
96   1.0   1   3      육류 에피타이저            1  술린이 연인과함께
100  1.0   1   3         육류 양식            1  술린이 연인과함께
114  1.0   1   3        육류 해산물            1  술린이 연인과함께
152  1.0   1   3  육류 해산물 에피타이저            1  술린이 연인과함께

      도수  당도  산도                      음식  상황별추천 군집화_n   상황별추천 군집화
14   6.0   4   3       육류 sweet디저트 에피타이저            2  달콤한 친구와 함께
16   6.0   5   3       육류 sweet디저트 에피타이저            2  달콤한 친구와 함께
75   8.0   5   3             육류 해산물 매운음식            2  달콤한 친구와 함께
77   8.0   5   3                sweet디저트            2  달콤한 친구와 함께
80   8.0   5   2                sweet디저트            2  달콤한 친구와 함께
86   7.0   3   3                   육류 양식            2  달콤한 친구와 함께
87   7.0   1   3                   육류 양식            2  달콤한 친구와 함께
88   7.0   1   3         육류 해산물 양식 에피타이저            2  달콤한 친구와 함께
128  7.0   4   3            육류 해산물 에피타이저            2  달콤한 친구와 함께
137  7.0   5   3                     디저트            2  달콤한 친구와 함께
154  5.0   5   3  육류 매운음식 sweet디저트 에피타이저            2  달콤한 친구와 함께
165  7.0   4   3          sweet디저트 에피타이저            2  달콤한 친구와 함께
172  5.0   5   3                sweet디저트            2  달콤한 친구와 함께
197  5.0   4   3                  육류 해산물            2  달콤한 친구와 함께
278  8.0   4   4                  육류 해산물            2  달콤한 친구와 함께
306  7.0   5   3                   에피타이저            2  달콤한 친구와 함께

       도수  당도  산도                     음식  상황별추천 군집화_n  상황별추천 군집화
10   14.0   1   3               육류 에피타이저            3  술른이 연인과함께
18   14.0   1   3            육류 양식 에피타이저            3  술른이 연인과함께
19   14.0   1   3           육류 해산물 에피타이저            3  술른이 연인과함께
20   14.0   1   3                     육류            3  술른이 연인과함께
23   14.0   1   3           해산물 양식 에피타이저            3  술른이 연인과함께
31   14.0   1   3                  육류 양식            3  술른이 연인과함께
51   14.0   1   3                    해산물            3  술른이 연인과함께
54   14.0   1   3              해산물 에피타이저            3  술른이 연인과함께
69   15.0   1   3            육류 양식 에피타이저            3  술른이 연인과함께
73   14.0   1   3      육류 매운음식 해산물 에피타이저            3  술른이 연인과함께
82   14.0   1   3       육류 매운음식 양식 에피타이저            3  술른이 연인과함께
83   14.0   3   3               육류 에피타이저            3  술른이 연인과함께
84   14.0   3   3                  육류 양식            3  술른이 연인과함께
85   14.0   3   3            육류 양식 에피타이저            3  술른이 연인과함께
107  15.0   1   3               육류 에피타이저            3  술른이 연인과함께
110  14.0   1   3       육류 매운음식 sweet디저트            3  술른이 연인과함께
129  15.0   1   3       육류 매운음식 양식 에피타이저            3  술른이 연인과함께
170  14.0   1   3              육류 해산물 양식            3  술른이 연인과함께
171  14.0   1   3     육류 해산물 양식 sweet디저트            3  술른이 연인과함께
175  15.0   1   3                  육류 양식            3  술른이 연인과함께
205  15.0   5   3         sweet디저트 에피타이저            3  술른이 연인과함께
215  14.0   1   3   육류 sweet디저트 양식 에피타이저            3  술른이 연인과함께
216  14.0   1   3  육류 sweet디저트 해산물 에피타이저            3  술른이 연인과함께
224  14.0   1   3        육류 해산물 sweet디저트            3  술른이 연인과함께
225  14.0   1   3                육류 중국음식            3  술른이 연인과함께
231  15.0   1   3                     육류            3  술른이 연인과함께
236  16.0   1   3                     육류            3  술른이 연인과함께
254  14.0   1   1                     육류            3  술른이 연인과함께
256  15.0   1   3           육류 해산물 에피타이저            3  술른이 연인과함께
266  14.0   1   3                 육류 해산물            3  술른이 연인과함께
271  14.0   1   3     sweet디저트 해산물 에피타이저            3  술른이 연인과함께
274  14.0   2   4           육류 해산물 에피타이저            3  술른이 연인과함께
292  15.0   1   2           육류 해산물 에피타이저            3  술른이 연인과함께
294  14.0   1   3               해산물 중국음식            3  술른이 연인과함께
295  14.0   1   2                     육류            3  술른이 연인과함께
297  15.0   1   2                     육류            3  술른이 연인과함께
301  14.0   2   3                  육류 양식            3  술른이 연인과함께
303  14.0   2   2                  육류 양식            3  술른이 연인과함께
304  17.0   2   2               육류 에피타이저            3  술른이 연인과함께
317  14.0   1   3                 해산물 양식            3  술른이 연인과함께
324  14.0   1   4               육류 에피타이저            3  술른이 연인과함께

       도수  당도  산도                          음식  상황별추천 군집화_n   상황별추천 군집화
26   11.0   1   3             육류 해산물 양식 에피타이저            4  화끈한 친구와 함께
52   10.0   1   3                          양식            4  화끈한 친구와 함께
66    9.0   2   3     매운음식 sweet디저트 해산물 에피타이저            4  화끈한 친구와 함께
68    9.0   4   3                    sweet디저트            4  화끈한 친구와 함께
74    9.0   4   3                 육류 해산물 매운음식            4  화끈한 친구와 함께
76   10.0   2   3                 육류 해산물 매운음식            4  화끈한 친구와 함께
78   10.0   4   3  에피타이저 해산물 매운음식 육류 sweet디저트            4  화끈한 친구와 함께
79   10.0   5   2                    sweet디저트            4  화끈한 친구와 함께
92   11.0   2   3          sweet디저트 해산물 에피타이저            4  화끈한 친구와 함께
111  10.0   2   3                 육류 해산물 중국음식            4  화끈한 친구와 함께
112  10.0   2   3              육류 해산물 양식 매운음식            4  화끈한 친구와 함께
122  11.0   5   3                    sweet디저트            4  화끈한 친구와 함께
155   9.0   5   3      육류 매운음식 sweet디저트 에피타이저            4  화끈한 친구와 함께
164  11.0   2   3                        매운음식            4  화끈한 친구와 함께
173   9.0   5   3           육류 sweet디저트 에피타이저            4  화끈한 친구와 함께
238  11.0   2   3                          육류            4  화끈한 친구와 함께
277  10.0   1   4                          육류            4  화끈한 친구와 함께
287  10.0   5   3              sweet디저트 에피타이저            4  화끈한 친구와 함께

In [235]:
wine_real_final.to_csv('wine_final_real.csv')